### ISSUE TITLE
Keyboard has a horrible Layout on rotated screens.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#105]
Look at the pictures. Only the first one isn't rotated.

![8vimRotated1](https://user-images.githubusercontent.com/59611881/100208093-9d494280-2f08-11eb-93de-c0af0f68747f.jpeg)

![8vimRotated2](https://user-images.githubusercontent.com/59611881/100208091-9d494280-2f08-11eb-9b6b-a86970200c20.jpeg)

![8vimRotated3](https://user-images.githubusercontent.com/59611881/100208088-9cb0ac00-2f08-11eb-9eff-3a93092db004.jpeg)

**Comment by Glitchy-Tozier** [comment]
The third is the worst. But the second is... really awkward as well.

**Comment by flide** [comment]
This has been my pet peeve since the project started. see #5. 

Please continue this thread on #5
