### ISSUE TITLE
8vim's github description has errors.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#106]
https://github.com/flide/8VIM/

"_The application was started essentially as a clone of 8pen, which for some reason they have stopped distributing. (I can no longer install it even though when I paid for it!!!)_"

`even though when` is incorrect. I think it would be correct if `when` was deleted.

"_The application at first was created as a clone of 8pen, which for some reason they have stopped distributing. (I can no longer install it even though I paid for it!!!)_"

**Comment by flide** [comment]
taking the issue forward with #109
