### ISSUE TITLE
[Bug/Feature] Keyboard should reset when closing/re-opening

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#107]
Currently, if you wrote a few symbols using the symbol&number-keyboard in ... let's say Whatsapp, and then you exit out, go into your browser and want to search for something, 8vim opens up to the same symbol&number-keyboard.

As far as I know, it's common practice to always open a keyboard up with the letter-layer. Even if you stay within the same application.

Whenever 8Vim is opened, it should display the regular letter-screen.

**Comment by flide** [comment]
Valid point. bug noted.
