### ISSUE TITLE
Rewrite 'Readme' to be more clear

### ISSUE THREAD

**Issue by m-rey** [8VIM/8VIM#109]
While I've already done some work in #108, it might be nice to rewrite the story of how this keyboard started. It's unclear how the described "keyboard with integrated editor" is related to the heavily 8pen inspired keyboard that this repository is for. Therefore, the back story about using editors and its problems, is somewhat confusing.

Also, some of the used expressions in the text might appear too crude for some. 

Furthermore, it appears that this keyboard was once the "keyboard with integrated editor" mentioned in the "Extended Idea" section. But now, it has changed to be something like a community created version of 8pen with extended features.

Maybe the "Idea" section should focus more on that. It could explain the concept the keyboard input method is based on, [quikwriting](https://en.m.wikipedia.org/wiki/Quikwriting). And add some perspective or roadmap about nice features that could be implemented in the future.

**Comment by flide** [comment]
Hey, can you make the changes you have in mind. I can start from there and start refining the README.
