### ISSUE TITLE
Unwanted control gestures registered after the last letter in a word

### ISSUE THREAD

**Issue by geofrey** [8VIM/8VIM#11]
Ending a gesture outside the circle (to avoid auto-spacing) should not trigger the control functions associated with each quadrant.

       2
       v
    3 > < 1
       ^
       4
For example, the letter 's' is center->2->3->center. The natural extension of this gesture would be to continue to quadrant 1. Currently, ending a drag in (1) tries to move the cursor to the right. Most of the time the cursor is at the end of a line and this does nothing, but other letters such as 'y' or 'g' or 'h' have the cursor moving backwards into the word we just typed. Quadrant 2 (move to the beginning of the line) is even more disruptive.

**Comment by geofrey** [comment]
It seems the editor commands are inferred and executed whenever we lift a finger from the screen, no matter what else that touch was doing before it ended.

**Comment by flide** [comment]
There are two points of processing the movements, first when the touch enters the circle and second when the touch is lifted off the screen.

**Comment by WuerfelDev** [comment]
Not sure if this is considered a bug or unwanted behaviour @flide but if you want to fix it you could add a variable boolean typed that disables all non-typing actions. The variable gets set to true once a letter has been typed, and the variable is reset to false when the finger is lifted

**Comment by flide** [comment]
@WuerfelDev seems like a good idea. I will try to add this logic in. Might take some time before I get to it.

**Comment by flide** [comment]
Okay, so my final solution is to distinguish between "new movement" and "continued movement" in the code. 
Once that distinction is made, I accept dpad commands only for "new movement". 

Sorry @geofrey , it took me 2 years to pick up the issue. I will try to do better.:)

**Comment by geofrey** [comment]
@flide no need to apologize, you're the one pushing code ; )
