### ISSUE TITLE
Give all keypads the same height (remove the bottom-margin of the X-board)

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#115]
Give all keyboards the same height.

The X-Board is higher than all the other ones. This feels very weird and makes the keyboard feel low-quality.

So I suggest: Remove the big bottom-margin of the X-board. This does two things:
1. makes all the keyboards have the same height.
2. makes the X-board look better.

**Comment by flide** [comment]
Can you post a screenshot please? I am not able to understand what is this 'bottom margin'.

**Comment by Glitchy-Tozier** [comment]
>I am not able to understand what is this 'bottom margin'.

The bottom thing is that "margin" I'm talking about. It's WAY bigger than the top one and there's no practical reason for this.

![8vimScreenshot1-edited](https://user-images.githubusercontent.com/59611881/100425431-7c5f2980-308f-11eb-8941-f2a2bb27e063.jpeg)


> Can you post a screenshot please? 

For screenshots of the other keyboards, just look at the Screenshots I posted in #77.

**Comment by Glitchy-Tozier** [comment]
>      For screenshots of the other keyboards, just look at the Screenshots I posted in #77.

You can even compare how much the keyboards cut off on Github in the background of those screenshots.

**Comment by flide** [comment]
Yep yep, I have fixed the mismatch of keypad heights as part of #47 but have introduced another bug while plowing through it. 

Currently, this is the only issue blocking next release. 

Regarding the empty space at the bottom, I will have to think it through. There exists  free space to be able to move the circle around to find a convinient position for the user. For example, i use it with it with my right hand and have moved the centre to the bottom right corner (see image). But indeed i see the issue in the screen shot you posted. 

![Screenshot_20201127-140717_GitHub.jpg](https://user-images.githubusercontent.com/7330631/100428379-df65b600-30b9-11eb-80e7-e29d9b9c7ee7.jpg)

**Comment by Glitchy-Tozier** [comment]
1. I really love how this looks. It's a great idea that you added those indicators of what the buttons do! Where can I give you feedback on those?
2. **Regarding the space:** I'm a little bit confused whether there still is a space or not as far as current development goes. You said two things:
>Yep yep, I have fixed the mismatch of keypad heights as part of #47 but have introduced another bug while plowing through it.

>Regarding the empty space at the bottom, I will have to think it through. There exists free space to be able to move the circle around to find a convinient position for the user. For example, i use it with it with my right hand and have moved the centre to the bottom right corner (see image). But indeed i see the issue in the screen shot you posted.

The first thing sounds like you already fixed it. The second thing sounds like you didn't do it yet.

**My thoughts:**
I don't see much reason behind purposefully introducing screen-space to make the user able to correct the positioning of the keyboard. This is why i have two ideas that could help.
1. (this is the worse of the two): If you really want to keep that drag-and-drop-keyboard-positioning functionality, you could do this:
Make the DEFAULT that there's no unnecessary space and that the keypad is centered. Users can then ENABLE "custom keyboard placement" and move it around, similar to what you did with the touch-trail colors.
2. An idea that could make this easier, solve this issue and also solve #110.

It's an easy two-step process.
1. Create the buttons I proposed here https://github.com/flide/8VIM/issues/110#issuecomment-734174280
2. Make them adjustable.
The keyboard simply moves to where the buttons don't exist.

**Comment by Glitchy-Tozier** [comment]
> It's an easy two-step process.

Kind of like this:
![thisSolvesAllOurProblems](https://user-images.githubusercontent.com/59611881/100462141-1774f500-30ca-11eb-8bb8-20ccd9cf30a9.jpeg)

**Comment by Glitchy-Tozier** [comment]
Maybe there's not enough space for the bottom/top three buttons, especially if we want to keep the keypad at the same height as the special-character-keyboards.

On the other hand, this could
1. Make everything easily adjustable
2. Properly use the empty space that's currently flooding the app.
3. Solve #110.

I'm thinking the bottom-buttons might waste too much space though. What do you think?
(If they're to big, the keyboard could simply be moved around by moving the two vertical button-rows.)

**Comment by flide** [comment]
wow!! When did you post these. How did I miss so many comments!!

So, I have fixed up the height consistency issue. All keypads have same height.
With couple more changes, We should be able to have new release coming Friday.

Maybe your major concerns would be fixed up as soon as keyboard height becomes configurable, because the user then would be able to remove extra spacing by just reducing the height, and adjusting the center along side it... as I type, it sounds tedious... but still doable for now.

For clarity: 
- The keypads were originally not of same height
- I fixed the issue but introduced a new issue where the height of x-pad was lower then the rest when the keyboard is opened first time, it fixes itself eventually.
- fixed the height consistency finally today.
- keyboard height is still not configurable.

**Comment by Glitchy-Tozier** [comment]
>wow!! When did you post these. How did I miss so many comments!!

I can be very stealthy when I want to be  ;)

>All keypads have same height.
With couple more changes, We should be able to have new release coming Friday.

Great, looking forward to it!

>Maybe your major concerns would be fixed up as soon as keyboard height becomes configurable, because the user then would be able to remove extra spacing by just reducing the height, and adjusting the center along side it... as I type, it sounds tedious... but still doable for now.

As I said, it's probably best (if the user _can_ change the height manually) to keep the keyboard on the same size as the other ones, and let the user mess everything up themselves, instead of starting with a mess and then let the user fix it.

> • The keypads were originally not of same height

I see.

>• I fixed the issue but introduced a new issue where the height of x-pad was lower then the rest when the keyboard is opened first time, it fixes itself eventually.

That's unfortunate.

>• fixed the height consistency finally today.

Does that mean you already fixed the new temporarily-lower-X-board-bug?

**Comment by flide** [comment]
Yes, the 'temporarily-lower-x-pad' bug is fixed.

**Comment by Glitchy-Tozier** [comment]
Nice, looking forward to seeing the update in action!
