### ISSUE TITLE
Visually improve the special-character-keyboards.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#116]
Unfortunately these keyboards are kind of ugly.
________________________________
![8vimScreenshot2](https://user-images.githubusercontent.com/59611881/100383223-657fef00-301d-11eb-8fbd-3ebc45f293ac.jpeg)
________________________________
![8vimScreenshot3](https://user-images.githubusercontent.com/59611881/100383222-657fef00-301d-11eb-9687-593db8f01ac0.jpeg)
________________________________
![8vimScreenshot4](https://user-images.githubusercontent.com/59611881/100383220-64e75880-301d-11eb-9026-f7fe960b4a61.jpeg)
________________________________

The selection keyboard (the top one) is the least problematic. But let's point out some flaws:
- Buttons aren't visibly buttons. They are just black shapes on a white surface. Show the user the borders (with rounded edges please, just as it's the case with regular keyboards)
- Somehow indicate what those white spaces do in the selection keyboard. I really like them and what they do, but they should not just be a white space on the keyboard.
- Many symbols are very small. We have enough space to display them a little bigger.
- The enter-symbols on the two are **tinyyyy**! Please make them bigger.
- Special buttons (like DELETE, ENTER, and SWITCH KEYBOARD should be styled differently than the others to signify their difference.
(actually, even style DELETE and ENTER differently from SWITCH KEYBOARD, as they are editing-buttons and not menu-buttons.)
- For some reason, that `-->|`-icon creates a `=`. No idea what it should do, but that's probably not it.
- The two special-character-keyboards have the same number of rows and columns, yet they still somehow aren't aligned the same way. To test this, just rapidly tap the `123` and the `{+=`-button and watch everything move. This shouldn't happen.
- On the third keyboard, we have room for one more character on the left of the space-bar-button. Use it.
- The `{+=`-button is straight-up incorrect. The keyboard it opens doesn't contain either `+` or `=`. Just `{`.
- All the pop-ups are just white.

**Comment by Glitchy-Tozier** [comment]
>On the third keyboard, we have room for one more character on the left of the space-bar-button. Use it.

What would be a good contender?

**Comment by flide** [comment]
Possibly related to #68

**Comment by flide** [comment]
@Glitchy-Tozier Can you move your original comment to the #68 and close this please.

**Comment by Glitchy-Tozier** [comment]
Done.
