### ISSUE TITLE
bottom cutoff in numbers mode 

### ISSUE THREAD

**Issue by caseyng** [8VIM/8VIM#117]
the bottom of the numbers board is cut off. 

running 8vim on vivo v15, android 10. please see attached picture. 

![Screenshot_20201127_103108](https://user-images.githubusercontent.com/75104423/100404162-acacc500-309b-11eb-8c1d-44f8a11c3691.jpg)

**Comment by BruceMustache** [comment]
not just the numbers 
my normal keyboard is cutted too 
In my case think a solution should be adjust the font acording to keyboard size
