### ISSUE TITLE
suggestion: two x-boards 

### ISSUE THREAD

**Issue by caseyng** [8VIM/8VIM#118]
why not have two x-boards, side-by-side? one for characters and the other for numbers and symbols? 

this can reduce the need to toggle between boards.

**Comment by flide** [comment]
check #110

if you feel the other thread answers your curiosity, close this one.

**Comment by Glitchy-Tozier** [comment]
> check #110

https://github.com/flide/8VIM/issues/110#issuecomment-734280934 speciffically
