### ISSUE TITLE
Template issues

### ISSUE THREAD

**Issue by BruceMustache** [8VIM/8VIM#124]
Create template issues for features and bugs

**Comment by flide** [comment]
@BruceMustache I think your suggestion is great, can you point me to some reference templates that have worked for you or your projects before?

**Comment by BruceMustache** [comment]
@flide I think you would like templates from https://github.com/minetest/minetest and https://github.com/TeamNewPipe/NewPipe projects

**Comment by flide** [comment]
Thanks, I will take a look

**Comment by flide** [comment]
done
