### ISSUE TITLE
Make Touch-Trail-Buttons Colorful again.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#129]
The buttons used to have nice colors. Please make them colorful again.
Currently, they just are gray.

![Screenshot_20201203-153916_8Vim.jpg](https://user-images.githubusercontent.com/59611881/101042665-b8a5f480-357d-11eb-905a-bade12fb93ff.jpg)

**Comment by flide** [comment]
We will be removing the buttons altogether and provide a colour wheel or something similar to select the color for the trail.
