### ISSUE TITLE
Top and bottom cut off on Nokia 5.3

### ISSUE THREAD

**Issue by DocMcSnappen** [8VIM/8VIM#134]
I'm a new user of 8vim.  On a stock Nokia 5.3 (Android 10), the top and bottom of the keyboard are cut off and letters/symbols are missing from view as a result.  See attached screenshot.
![Screenshot_20201210-085845](https://user-images.githubusercontent.com/75794812/101784070-0a440700-3ac9-11eb-9ee2-76b88ec7debe.png)

**Comment by DocMcSnappen** [comment]
Forgot to say - this also happens on iteration 5, but only when 3-Button Navigation is enabled (see screenshot).  If I switch Android to Gesture Navigation on iteration 5, it displays as expected.
![Screenshot_20201209-183103](https://user-images.githubusercontent.com/75794812/101784410-7888c980-3ac9-11eb-973e-51d92b23910b.png)

**Comment by Glitchy-Tozier** [comment]
That's disgusting.

Edit: I think I might know where this came from! Did you install it from f-droid? Is it "Iteration 5"?

**Comment by DocMcSnappen** [comment]
Initially, yes. That's the second screenshot.  I (weirdly) couldn't update to iteration 6 - I had to uninstall, then install the Play Store version to get 6 (first screenshot).

**Comment by Glitchy-Tozier** [comment]
I see.
Yeah, the update was … let's say weird  xD

Ok, if it still persists in iteration 6, it's a new bug.

**Comment by DocMcSnappen** [comment]
To be clear, the very first message & screenshot are iteration 6. I apologize for neglecting to say so initially.

**Comment by nullbasis** [comment]
I have the exact same issue in Iteration 6, installed from F-Droid today.
