### ISSUE TITLE
Usability Guide suggested update for dead link

### ISSUE THREAD

**Issue by DocMcSnappen** [8VIM/8VIM#135]
The [Usability Guide](https://github.com/flide/8VIM/wiki/Usability-Guide) links to 8Pen on Google Play to learn how to use the keyboard.  But that link is dead, 8Pen is gone, and so is its game.  For me, this [old YouTube video of 8Pen](https://www.youtube.com/watch?v=q3OuCR0EpGo) was super helpful in learning the keyboard - albeit with a different layout - but it got me started.  Ideally, 8Vim would have its own video etc, but for now maybe use the old YT video instead of dead links?

**Comment by flide** [comment]
Sure, we can. But, time is finite for me... would you be willing to fix them on the wiki?

**Comment by DocMcSnappen** [comment]
I don't seem to have edit access to the wiki, but here's my suggested update.  It includes an updated link, improved grammar, and hopefully improved readability.  I also removed the Selection & Paste information since that seems to be outdated.  (Swiping Right->Circle instead opens the Nav/Copy/Paste panel.)  Please correct anything I got wrong, or bring it to my attention and I'll go over it again when I have time.

::::::

Getting started with 8Vim can be tough at first.  Check out this YouTube video of 8Pen (the forerunner of 8Vim) to see how it works.  The layout of 8Vim is a little different, but the concept is the same:

https://www.youtube.com/watch?v=q3OuCR0EpGo


Sectors
Notice how the keyboard is divided in 4 sectors?  If you tap once on a sector, these are the effects:

Right Sector acts as a Backspace key
Left Sector acts as a shortcut to the Number Pad
Top Sector acts as a combo Shift & Caps Lock key (i.e, Press once for Shift, Press twice for Caps Lock, and Press once more and everything is back to usual)
Bottom Sector acts as an Enter key


Cursor Movements
If you move your finger from the center-circle to any sector and stay, the cursor will instead will move that direction. For example, if you swipe from circle->right, the cursor will move right. You get the picture.

Text selection is also built into the keyboard. If you move your finger from the right sector to the circle, it will switch to the copy/paste aspect of the keyboard (which includes cursor movement arrows).

**Comment by flide** [comment]
@DocMcSnappen Can you please check again regarding the wiki access. It seems it was set to collaborators only. I have reset it to accept contribution.

**Comment by DocMcSnappen** [comment]
Finally had time to make the edits.  Hopefully this is more clear & helpful now than before.
