### ISSUE TITLE
Using machine learning to come up with the best layout

### ISSUE THREAD

**Issue by akrivka** [8VIM/8VIM#14]
I've had a crazy idea, whilst being unhappy with the placement of the character 'y' on the keyboard, which at least in my mother language doesn't get used very much.

What if we could define _smoothness_ of a gesture (finger movement, mathematically a discrete curve) and give it, with the input being a ton of text from books, articles, websites, ..., to a machine learning algorithm, that would try different layouts of the characters to find the ultimate best one that accomplishes most common bigrams or whole words in smooth, flowing gestures. What I mean by that is that you wouldn't need to change the direction of the movement of your finger much (e.g. typing 'no' on the current layout).

What are your opinions on this? I might take this as a project that I would do in my free time. (which is not guaranteed to exist...)

**Comment by flide** [comment]
Well the idea is not so crazy and was originally a key concept for the letter distribution on 8pen, which I copied over for English. 
But yes, if only we could define the "smoothness" it would be great and we might be able to generate other language boards with relative ease. If you are interested in taking this forward, you might want to start with the following document.
http://www.michaelfester.com/data/8penresearch.pdf

**Comment by flide** [comment]
Hey,

Your mail finally found me... sorry for that.

Your idea is actually pretty great. If VI8 is to be extended to other
languages, that would be the way to start the design process for it.
Did you ever get to start on your proposal?

Regards,
Ravi

**Comment by akrivka** [comment]
Hey, I didn't build on the idea, because of other occupations, but I still consider mobile input methods a significant issue and an AI-generated layout a promising solution. Sadly, I don't have enough experience with machine learning and mobile development, so this idea is up-for-grabs.

**Comment by flide** [comment]
Thanks, may be I will catch it someday :)

**Comment by Glitchy-Tozier** [comment]
> What if we could define _smoothness_ of a gesture

I think those are some important points to consider:
1. The most common letters of a language should require the smallest loops.
2. The most common letter-combinations (words) should be constructed by as many straight lines as possible (the thing you mentioned, @flide. "no" would be a bad situation while "to" would be perfect. Basically, what 8pen apparently called “low energy”.

Actually, that document _http://www.michaelfester.com/data/8penresearch.pdf_  you mentioned is really great and already mentioned all my thoughts...

**Comment by flide** [comment]
Is it possible on github to merge 2 issues, so that they can be tracked together?

**Comment by flide** [comment]
Closing this one. Please put your thoughts on #20 .

**Comment by Glitchy-Tozier** [comment]
> Closing this one. Please put your thoughts on #20 .

Does that mean thoughts should be copied there or should new ones just be posted there?

**Comment by flide** [comment]
preferably both, but won't hurt in either case.
