### ISSUE TITLE
Add rapid-fire on the center-circle of the X-board

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#141]
Basically: add `space`-rapid-fire.

**Comment by flide** [comment]
My issue with this feature is the following:

The center is the natural resting place for my thumb when I am tying but have paused to process my thoughts. With this feature in effect, the pause will cause lot of spaces, distracting me...

Do we really need a space rapid fire?
If you want, we can mod the "tab" button to effectively enter 4 or 8 spaces. Currently, the tab button is useless as it moves the cursor away from the input field anyways.

**Comment by Glitchy-Tozier** [comment]
> The center is the natural resting place for my thumb when I am tying but have paused to process my thoughts. With this feature in effect, the pause will cause lot of spaces, distracting me...

I understand. This sounds like a big problem.

I have an even better idea though:
1. We don't need the circle-rapid-fire... In the case that we need many spaces, we can just switch to one of the special-character-keyboards. Those `space`s should be able to rapid-fire anyways.
2. Using a whole button (tab) just for space-ramid fire seems like a waste to me. I'm sure we can come up with better ideas in the future!

**Comment by Glitchy-Tozier** [comment]
> The center is the natural resting place for my thumb when I am tying but have paused to process my thoughts. With this feature in effect, the pause will cause lot of spaces, distracting me...

I understand. This sounds like a big problem.

I have an even better idea though:
1. We don't need the circle-rapid-fire... In the case that we need many spaces, we can just switch to one of the special-character-keyboards. Those `space`s should be able to rapid-fire anyways.
2. Using a whole button (tab) just for space-ramid fire seems like a waste to me. I'm sure we can come up with better ideas in the future!

**Comment by flide** [comment]
closing this thread
