### ISSUE TITLE
Add framework for adding Languages

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#144]
Prepare 8Vim for adding new languages.

#### Here's a few to-do's:

- Add the possibilities of having multiple layouts in one app
- Add menu-options in the settings for switching layouts.
- Make it possible to have **two layouts of the same language** in the app (for example: New English layout & Old English layout for people who don't want to switch)
- Give the layouts name-tags and display a description. (for example, describe what the old/new layout is)

- (Also add an option for custom Layouts)

This is something I suggest working on soon, to prevent having to wait for a long time, once the language-specific Layouts arrive.

**Comment by ghost** [comment]
If you start to implement different language layouts you could also consider to add a framework to localize the settings screen for supported languages and maybe the texts used in app-stores.
I know this is actually of minor importance but it adds a lot to the look and feel of the app.
Cheers,
Gecko

**Comment by flide** [comment]
@GeckoClimber Yea, that would also come up as time passes, for now I won't be able to setup localization.

**Comment by flide** [comment]
@sslater11 @Glitchy-Tozier, The basic framework is almost ready for the layout selection.
If you guys are interested, I can setup alternate English by sslater11 and German by Glitchy-Tozier for this first draft.
This will allow me to test the multiple language setup and multiple layouts within a language setup properly.

**Comment by Glitchy-Tozier** [comment]
That sounds great. Let's make a temporary layout!
(Personally, i haven't used 8vim much, so I need some experience to know what movements flow well)

@sslater11 are you willing to try out the best computer-generated layout I can find for the english language? Or do you prefer to test out your manually created one for now?

**Comment by Glitchy-Tozier** [comment]
Also, @flide, does this already include some diacritics-movement?

**Comment by flide** [comment]
no diacritics yet, that is the reason I wanted this first draft with all
german characters included.

Give me your best draft and one with all character, I will try to make
diacritcs work for german language only.

**Comment by Glitchy-Tozier** [comment]
# Best English Draft
Here's the best English draft I found:
```
Layout:
eotdnraisgcfumlhyvkxbjwpq---z---
Score: 3367449715.66    ~86.89 %
Layout-placing: 1
```
Number 2 and 3:
```
Layout:
eotdnraisgcfumlhyvkxbjwpq-z-----
Score: 3367388851.57    ~86.89 %
Layout-placing: 2

Layout:
eotdnraisgcfumlhyvkxbjwpqz------
Score: 3367352431.84    ~86.89 %
Layout-placing: 3
```
For comparison: 
```
Old / original 8VIM layout:
eitsyanolhcdbrmukjzgpxfv----q--w
Score: 3149976802.24    ~81.28 %

English layout by sslater11:
hitanerolfydmcsujwkgpxbv----q--z
Score: 3204728468.29    ~82.69 %
```

# Best German Draft
Here you go:
```
Layout:
eatnsruidclmobghkpyfvjwzq-----x-
Score: 711366381.9    ~90.77 %
Layout-placing: 1
```

In case this wasn't clear, this is what that means:
![8vim_G_LayoutFinalDraft](https://user-images.githubusercontent.com/59611881/103029545-5035ac00-455a-11eb-94ec-e4063cae1651.jpg)

I guess we can fill it up like this:

![8vim_G_LayoutFinalDraft2](https://user-images.githubusercontent.com/59611881/103029986-2e88f480-455b-11eb-9b93-e5f0152eb76f.jpg)


Keep in mind: **THIS LAYOUT IS NOT OPTIMIZED FOR DIACRITICS!! WHATEVER DIACRITIC-MOVEMENT WE PICK, THERE'S PROBABLY A BETTER LAYOUT OUT THERE.**
(also, please rotate the layout 180°)


_____________________________
Also @flide, what do you think about this? https://github.com/flide/8VIM/discussions/65#discussioncomment-235516
I think it could be more useful than our currently planned movement. Also,
1. It could be easier to implement into 8-vim
2. It gives us more options for easy diacritics
3. It _definitely_ is easier to implement into my layout-calculator.

**Comment by Glitchy-Tozier** [comment]
Damn it, I forgot about `ß`.
I guess
1. Swap `,` and `?`
2. Then exchange `?` for `ß`

**Comment by Glitchy-Tozier** [comment]
> Give me your best draft and one with all character, I will try to make diacritcs work for german language only.

That means that you'll implement those layouts in iteration 7, right?
(Of course, they should clearly be labeled as **Temporary layouts, for testing purposes only!** or something of the likes)

**Comment by flide** [comment]
Yea, I am trying to.

**Comment by flide** [comment]
Sorry, moved to iteration 8

**Comment by adaschma** [comment]
I have published a version with @Glitchy-Tozier's layouts: https://github.com/adamschmalhofer/8VIM/releases/tag/devel-1

As we now have diacritics, I'm kind of curious how the optimal layout once that is considered.

**Comment by Glitchy-Tozier** [comment]
@adamschmalhofer If you're curious: Pretty sure i wanted the layout rotated because of the diacritics gesture that was considered at the time (which I still think would be one of the best options)

EDIT: I assume @kjoetom has found the best english layout so far, should you ever look for an expert. I can't find our discussion, but he might know what issue/discussion we were using.

**Comment by flide** [comment]
Hi All,

With the help of @adamschmalhofer 's contribution, I have been able to setup a framework for adding layouts easily.

To add a new layout following needs to be done:

    Develop a keyboard-data xml file.
    Name the file with following format [{language-iso-code}_{font-code}_{layout-name}]
    Place the file in the raw folder

    Language code is the 2 character code for the language as per ISO standard
    Font code is one of the following strings, and as of now only "regular" is going to function properly : "regular", "bold", "italic", "underline"
    Layout name is the display name of the layout

In the settings menu the layout would be presented as "Layout name (Language)"

The characters for the layout are now part of the keyboard-data file itself.
Please check the "he_regular_hebrew" file in the raw folder for reference.

I will request all to open one PR per layout.
