### ISSUE TITLE
Wrong Values are Displayed in Settings

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#148]
Reproduce:
1. Reset keyboard (go into settings and clear the cache & storage of the app. Reinstalling might work as well)
2. Go to the settings
3. Click on Resize Circle
4. You should see the value 0.10.

That value is wrong. If you manually set the value to 0.10 after moving the slider around, you'll see how small 0.10 is.

**Comment by MichalLebeda** [comment]
@flide This seems to be fixed by #172  to me

**Comment by Glitchy-Tozier** [comment]
There has been no update since I posted this, so it may just be your phone.

**Comment by MichalLebeda** [comment]
*edited previous comment so it makes sense*

**Comment by Glitchy-Tozier** [comment]
Ah okay, in that case, great!  :)
