### ISSUE TITLE
Sidebar-buttons are cut-off.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#149]
Look at this picture:
![Screenshot_20201222-081222_GitHub.jpg](https://user-images.githubusercontent.com/59611881/102860128-7f9aca80-442d-11eb-8f88-23acc868d665.jpg)
I thought this just was a natural result of making the keyboard less high, but apparently, this only happens on some devices.
So I thought i should post about it.

**Comment by flide** [comment]
How did you make it "less high"?

**Comment by Glitchy-Tozier** [comment]
I didn't. You did. In Iteration 6.

**Comment by flide** [comment]
it might be because side-bar is the only component with fixed height...

**Comment by flide** [comment]
This should be part of the existing open enhancement #47 
I will leave this open for now, hopefully it can be close as #47 closes. I hope @Glitchy-Tozier you would be able to help me with the verification of the bug.

**Comment by flide** [comment]
With one of the commits for #47 , the sidebar no longer has a fixed size and is dependent on the size of the x-pad view.
This is hopefully fixed. I have no way to test this. marking this as fixed.
