### ISSUE TITLE
Selection keypad/xboard issues

### ISSUE THREAD

**Issue by efficientwrite** [8VIM/8VIM#152]
There, are a few issues noticed in selection keypad and xboard.

1. When using the arrow keys, text are highlighted but copy/cut doesn't work but paste works.
2. In xboard layout ctrl key is shown, there can be a highlight when Ctrl key is selected.
3. Pressing Ctrl + v on xboard pastes content(ctrl x works) but Ctrl + a doesnt work as expected it selects the text but also the text is removed.
4. When ctrl commands are used do not insert space.
5. Also could a space button and select all button in selection keypad.

Using iteration 6 version.

**Comment by flide** [comment]
1. I have never observed selection keypad buttons not responding, can you provide details to duplicate the issue please? like which app were you using where you saw this happening and anything specific I need to do for replication? 

2. noted, but by popular demand we might end up removing the 'ctrl' key in few iterations. 

3. workaround - after pressing 'ctrl' and typing 'a' don't lift the finger but move in to any sector and lift. 

4. This is a little tricky to implement and the above workaround alleviates the issue anyways. If there are a few complains, I will open an issue for the same. 

5. select-all button already exists in selection keypad, second button in the last row. Space button can be added... but doesn't feel like it should be part of selection keypad, but then enter key is already part of it... will have to think about it.

**Comment by flide** [comment]
I think I should remove 'enter' from the selection keypad.

**Comment by efficientwrite** [comment]
For the first one will add a screen grab.

https://user-images.githubusercontent.com/40225391/103329327-33b2db80-4a54-11eb-8ba7-a6388b309eb3.mp4


For the last, didn't notice properly about the select all icon, just suggested space button as there are empty places and isn't essential.

**Comment by flide** [comment]
I don't know how to replicate the issue, copy paste works properly for me.
