### ISSUE TITLE
Cursor movement issue

### ISSUE THREAD

**Issue by efficientwrite** [8VIM/8VIM#153]
When moving from the center of the circle to the right sector cursor movement is emulated. In some apps this doesn't work well like firefox and  idm where trying to move the cursor from left to extreme right by moving from center to right and keep holding and release in right sector cursor is stuck on moving right and doesn't stop on reaching the end. Issue also applies for left movement.

https://user-images.githubusercontent.com/40225391/103257360-d00fac00-4988-11eb-966d-0c6a681f297c.mp4

**Comment by Glitchy-Tozier** [comment]
Possibly a duplicate of or related to #58 and #81.

I think the rapid-fire is fine as long as you hold the button, but it shouldn't go on spamming.

**Comment by flide** [comment]
@gokulraam what version are you using currently?

**Comment by efficientwrite** [comment]
Using iteration 6 version.

**Comment by flide** [comment]
Okay, I understand the issue now. 
The problem is that the cursor is not bound and as d pad keys are being worked,  cursor might jump out of the input box.

Am I right @gokulraam ?

**Comment by efficientwrite** [comment]
Cursor jumps out of the box is one thing and cursor is supposed to stop at the end of the word/sentence after reaching the end but it doesn't. Also yes cursor loses focus and input text is emptied and keyboard closed on left cursor   movement at start of input in bromite app but the right cursor stops at end of input in bromite. Right cursor goes on spamming in apps like firefox. While cursor movement is rapid fired, cursor focus should not go out of the given input box.

**Comment by Glitchy-Tozier** [comment]
I think, we can summarize this as two problems:
1. Cursor selects elements outside of the text-field
2. Arrow-Key gets stuck on rapid-firing. after leaving the text-field

**Comment by Glitchy-Tozier** [comment]
But if we remove the fact that arrow keys can go outside the textbox, we should not remove the Tab key.

Enter = New line + (sometimes) next textbox
Tab = Next textbox, even if Enter creates Line Breaks.

**Comment by flide** [comment]
need better undestanding

**Comment by flide** [comment]
As @Glitchy-Tozier consolidated the original issues :  

1. Cursor selects elements outside of the text-field

This is kind of a feature, which was never intended, but which many folks like. So, it's here to stay.

2. Arrow-Key gets stuck on rapid-firing. after leaving the text-field

This has been fixed with iteration-7
