### ISSUE TITLE
Give Textbox in Settings the Same Margin as Buttons

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#156]
Currently, the textbox for testing the keyboard doesn't have any margins. It sticks to the sides of the screen while the buttons are nice and centered.

![Screenshot_20210101-113126_8Vim.jpg](https://user-images.githubusercontent.com/59611881/103437238-74158380-4c25-11eb-818a-6c78450df806.jpg)

**Comment by Glitchy-Tozier** [comment]
Proposal: Make text-bar shorter.
(Also, make it bigger if the user types an `Enter`)

![20210101_114152.jpg](https://user-images.githubusercontent.com/59611881/103437322-83e19780-4c26-11eb-905c-1a347939d29b.jpg)

**Comment by flide** [comment]
noted.

**Comment by MichalLebeda** [comment]
@flide Not relevant anymore

**Comment by Glitchy-Tozier** [comment]
1. Hi :)
2. Looking forward to seeing what you have changed.
(Btw, you might know this already but you can add "`Closes #156`" to your PR and the issue should get closed once flide accepts it.)
(Should also work with `fixes #xxx`)

**Comment by MichalLebeda** [comment]
@Glitchy-Tozier thanks, didn't know that
