### ISSUE TITLE
Fix release tag name 

### ISSUE THREAD

**Issue by f1reflyyyylmao** [8VIM/8VIM#162]
The currently newest release tag is Iteration-6, which breaks the f-droid build since the naming convention was iteration-# with a lowercase 'i'. It'd be great if this could be solved so the changes get picked up by f-droid :)

**Comment by flide** [comment]
ohh... I was so confused why f-droid was not picking up the release. Thanks
for the info.

**Comment by TheLastProject** [comment]
I fixed it manually for now: https://gitlab.com/fdroid/fdroiddata/-/commit/f11ca036e3cbb3f373b3cd6107c17287a60c8f17. Should have iteration-6 picked up soon.

Please ping me the next release so I can double-check stuff again. I think this is an F-Droid bug: https://gitlab.com/fdroid/fdroidserver/-/merge_requests/872

**Comment by TheLastProject** [comment]
The build was succesful, it should show up in the index soon-ish: https://f-droid.org/wiki/page/inc.flide.vi8/lastbuild_6

**Comment by f1reflyyyylmao** [comment]
Thank both of you for your time and attention to the issue
