### ISSUE TITLE
A space is appended to every button when I end a gesture on the circle

### ISSUE THREAD

**Issue by bodqhrohro** [8VIM/8VIM#163]
Am I doing something wrong? :)

I didn't try the original 8Pen, but this looks like a recognition problem.

**Comment by ThomasAH** [comment]
This is intentional: Don't lift your finger, but continue drawing letters until the word is finished.
At first this is sometimes quite hard, when you have to look at the letters to see where you have to continue, but just hold your finger on the circle until you know where to go next.

**Comment by raphael-proust** [comment]
Also, you can draw the path for one letter, get back into the circle to validate it, and get out of the circle again to enter the letter without the space. Also works for a complex path of multiple letters.

(Not sure if this is intended UX or if the program just inserts a space when you lift from the central circle.)

**Comment by bodqhrohro** [comment]
> get out of the circle

Yeah, much better, thanks.
