### ISSUE TITLE
Constant flickering of the trail

### ISSUE THREAD

**Issue by kuba-orlik** [8VIM/8VIM#164]
When typing with the keyboard, the trail is constantly blinking/flickering, which is very distracting (and can be problematic to people with epilepsy). 

You can see the problem in effect in this video:

https://video.kuba-orlik.name/videos/watch/9ecfac79-a1bd-4e34-be74-ede914747432

I'm on 8vim `iteration-6`, Android 8.1.0 (LineageOS), LG Nexus 5X

**Comment by Glitchy-Tozier** [comment]
As far as I can recall, this also happened on a Samsung tablet... unfortunately I can't recall whether it was iteration 5 or 6 and what exact model it was.

**Comment by fynngodau** [comment]
I’ve had this on Android 9 but once I upgraded to Android 10 the issue was gone.

**Comment by MichalLebeda** [comment]
@flide probably fixed by #172 but needs testing

**Comment by npostavs** [comment]
I can confirm 172 fixed this for me. (Android version 8.0.0, Galaxy S7)

**Comment by flide** [comment]
Thanks for the confirmation.
