### ISSUE TITLE
Ability to "backtrack"

### ISSUE THREAD

**Issue by kuba-orlik** [8VIM/8VIM#165]
What I mean by backtracking is when moving the finger around the center sometimes I move one bar too far and I want to move back, but when I do go back one bar and come back to the center, the letter isn't entered. You can see the issue in the video demo below:

https://video.kuba-orlik.name/videos/watch/804fbf84-19d3-4a66-b223-24d105dc3658

**Comment by flide** [comment]
So the characters are defined as 'path taken' in the code. For example, 's' is typed when the path is center-top-left-centre, now when you backtrack, the path is no longer the same. I use this to add more characters sometimes. For example, if you go center-top-left-top-left-centre what you will get is not 's' but 'ŝ'. 

So, I understand the your frustration, but you will have to work on the typing accuracy.

This is not a bug.
