### ISSUE TITLE
Add option to remove auto-spacing.

### ISSUE THREAD

**Issue by tkjhamak** [8VIM/8VIM#168]
I'm enjoying the keyboard, but the auto-space on release means a lot of backspaces. I.E when typing auto-space; typing passwords with case changes and/or numbers and special characters; using anything where space is a default keybind (visidata in termux). Awesome work though.

**Comment by flide** [comment]
Thanks :)

**Comment by ThomasAH** [comment]
You can avoid the space by ending your movement outside the circle.

If such an option would be implemented, it might be useful to still add the space if ending outside the circle, i.e. invert the current behavior.

**Comment by tkjhamak** [comment]
des

> You can avoid the space by ending your movement outside the circle.
> 
> If such an option would be implemented, it might be useful to still add the space if ending outside the circle, i.e. invert the current behavior.

**Comment by tkjhamak** [comment]
That does work, thanks! I feel like the option would be a great improvement though. It doesn't take long to press the center to add a space.

**Comment by flide** [comment]
Think about it in terms of something like cursive writting, you don't need
to pick your pen up from paper for every character and once the word is
complelete the space is automatically inserted.

I understand this becomes an issues when entering passwords and id's that
don't make sense as a 'word', but the use case is infrequent in real life.

Maybe we can disable the autospacing for password fields, but I guess that
would be the extent of it.

Regards,
Ravi

**Comment by tkjhamak** [comment]
I suppose my use case isn't the norm, so that makes sense.  I mostly wanted a reliable keyboard for TUI's since small touch screen keyboards are horrendous in Termux and this one seems precise. 
I'll just keep switching keyboards for now. I appreciate the quick response and your time. Best of luck on all your projects.
