### ISSUE TITLE
Material design

### ISSUE THREAD

**Issue by MichalLebeda** [8VIM/8VIM#169]
Hi I would like to implement material design according to the guidelines. My question is: Should I do it or  this app uses custom theme on purpose?

**Comment by flide** [comment]
Go ahead, give it a shot

**Comment by MichalLebeda** [comment]
I have tweaked settings a bit (WIP state)
![Screenshot_1619475529](https://user-images.githubusercontent.com/5246963/116158167-788f0c00-a6ee-11eb-99d9-c4648a6d74bf.png)

**Comment by flide** [comment]
looks nice, can you open a PR ?

**Comment by MichalLebeda** [comment]
I will, but it is not finished yet

**Comment by MichalLebeda** [comment]
Gonna fix settings persisting and then will make one ;)

**Comment by MichalLebeda** [comment]
@flide Do you know how to restart the keyboard? I want to apply new colors on preference change but don't know how to do it (for regular widgets not canvas). 
current state (I think the trail bug is much worse because of the emulator):  
![image](https://user-images.githubusercontent.com/5246963/116282749-6dd68480-a78b-11eb-9cd7-04d9965fe581.png)

**Comment by MichalLebeda** [comment]
current state 


![Screenshot_20210427-213903_8Vim.jpg](https://user-images.githubusercontent.com/5246963/116302200-2eb32e00-a7a1-11eb-9e3d-60df76fea7e5.jpg)

**Comment by MichalLebeda** [comment]
@flide Changes included in #172. This can be closed
