### ISSUE TITLE
Submit to F-Droid?

### ISSUE THREAD

**Issue by esmoak** [8VIM/8VIM#17]
This keyboard might get a larger following if it is listed on F-Droid.

Thanks for your work on this keyboard.

**Comment by esmoak** [comment]
I emailed you and you responded that you were receptive of this idea, so I put in the issue here for packaging:

https://gitlab.com/fdroid/rfp/-/issues/1466

Thanks again for the work on this app. 

@flide also including @m-scudder (not sure how involved you were in this, but saw that you contributed)

**Comment by esmoak** [comment]
Looks like this got picked up for @izzysoft repo. For now.

https://apt.izzysoft.de/fdroid/index/apk/inc.flide.vi8

Thanks Izzy for your generousity.

**Comment by esmoak** [comment]
Rough copy of fdroid error. See issue linked above:

Gradle Wrapper @ 64b2e99
gradle/wrapper/gradle-wrapper.properties is missing distributionSha256Sum, unverified gradle download! Here is an example of how to fix this:
#Sat May 30 21:24:11 IST 2020
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
distributionSha256Sum=10065868c78f1207afb3a92176f99a37d753a513dff453abb6b5cceda4058cda


gradle/wrapper/gradle-wrapper.jar does not match any listed on the official website: 10065868c78f1207afb3a92176f99a37d753a513dff453abb6b5cceda4058cda There is a gradle command for upgrading the wrapper:

**Comment by IzzySoft** [comment]
> Looks like this got picked up for @IzzySoft repo. For now.

That often happens, if the APK is available and attached to the tags/releases – to speed things up and shorten your waiting time. Inclusion process at F-Droid isn't exactly an express train :wink:

As for the gradle warning: doesn't affect inclusion, or even F-Droid builds (that gets replaced during the build process anyway) – but it's a hint to the author for their own builds, which are affected (just to give context: of course it's good to get it fixed).

Oh, and as pointed out on the RFP, we'd really like to have [Fastlane structures](https://gitlab.com/snippets/1895688) here for screenshots, description etc (details behind the link).

**Comment by flide** [comment]
Hey, thanks for the help. I am currently travelling but will try to get
this fixed asap.

Regards,
Ravi

**Comment by IzzySoft** [comment]
Great! Just mention here when it's done, I'll get a notification then so I can cross-check and further the RFP. Thanks!

**Comment by flide** [comment]
I have added the "fastlane" folder to the best of my understanding and also added the property "distributionSha256Sum" in the "gradle-wrapper.properties" file. Hopefully this should get it moving.

**Comment by IzzySoft** [comment]
Urn… you've missed one directory level. It should be `fastlane/metadata/android/…` – can you add the missing `metadata` level?

Then: `short_description.txt` is limited to 80 chars, and will be truncated at that place (so 242 chars would be dropped from yours). Suggestion for content: "vim-like keyboard and editor". `title.txt` is basically what the app name should look like inthe given language (at F-Droid, that's used for showing results in website search). All else should be fine with F-Droid.

**Comment by flide** [comment]
will fix it up.

**Comment by flide** [comment]
forgot to comment here, have fixed up the mentioned issues yesterday.

**Comment by IzzySoft** [comment]
Thanks! Just checked, looks good. Now that needs to be tagged with a "good tag name" – i.e. one that corresponds to either `versionName` (e.g. `v<versionName>`) or `versionCode` (e.g. `c<versionCode>`) to further the RFP.

**Comment by flide** [comment]
I am sorry, what change is required?

**Comment by IzzySoft** [comment]
A new [tag](https://github.com/flide/VI8/tags) needs to be created at `HEAD` with a name matching `versionCode` or `versionName` from the current [`build.gradle`](https://github.com/flide/VI8/blob/master/8vim/build.gradle), e.g.

    # choose: either by versionCode
    git tag c2
    # or by versionName
    git tag iteration-2
    # then push it to Github
    git push

That enables F-Droid 1) to automatically check for updates (verifying by comparing new tags against the `build.gradle`) and 2) to fetch Fastlane data (which is fetched from the same tag the app is built from).

**Comment by flide** [comment]
Done.

**Comment by IzzySoft** [comment]
Thanks! I've triggered a rescan by the bot at F-Droid, and with the results will setup metadata and mark it for the packagers to proceed. For future releases, please keep tag name and versionName in sync then, so they are detected automatically.

**Comment by flide** [comment]
Did this get picked up by f-droid? I wasn't able to search for it.

**Comment by IzzySoft** [comment]
You can check this yourself: as long as the RFP is still open, it was not yet integrated. Once it is closed via a merge request, metadata have been integrated – and you can check the build process for progress. Some [helpful links here](https://gitlab.com/snippets/1896503).

**Comment by flide** [comment]
It's Done!!

Now available on f-droid : https://f-droid.org/packages/inc.flide.vim8/

Thanks @esmoak and @IzzySoft

**Comment by IzzySoft** [comment]
So maybe now you want to update your ReadMe to

> Please get the latest release build from **F-Droid**

:smiley:

**Comment by flide** [comment]
not a bad idea :)

**Comment by Bubu** [comment]
Uhm... the appid was changed again...? That means we'll need to resubmit the new app to f-droid again? Why was it renamed back and forth so often?

**Comment by flide** [comment]
Because I am an idiot, see-sawing between cool and practical.
But this time it is firm. 8vim it is. never going to change it or it's app id. Promise!!

How do I initiate the resubmit?

**Comment by Bubu** [comment]
I can take that on, if you can confirm the appid one final time. It should be  `inc.flide.vi8` as currently in https://github.com/flide/8VIM/blob/master/8vim/build.gradle#L8 ?

**Comment by flide** [comment]
yes that is right `inc.flide.vi8`

**Comment by flide** [comment]
@Bubu , did you resubmit the app on fdroid?

**Comment by Bubu** [comment]
On October 28, 2020 9:34:25 AM GMT+01:00, Ravi Agarwal <notifications@github.com> wrote:
>@Bubu , did you resubmit the app on fdroid? 
>

Yes, it just got published:  https://f-droid.org/app/inc.flide.vi8

**Comment by flide** [comment]
nice!! it was quicker this time. lovely!!
Thanks @Bubu
