### ISSUE TITLE
Color themes

### ISSUE THREAD

**Issue by MichalLebeda** [8VIM/8VIM#170]
Screenshot shows nice looking minimalistic keyboard with black text on white background. Real app uses some red/white theme which looks a bit off. I would like to implement atleast 3 themes:
1. minimlaistic light
2. minimalistic dark
3. night mode red accented white

**Comment by Yquas** [comment]
@MichalLebeda Are you sure you uploaded a screenshot? I see no photos on your post.

**Comment by flide** [comment]
I am guessing @MichalLebeda was talking about the screenshots on either
gplay or fdroid.

**Comment by Yquas** [comment]
Oh ok, I understand. I also don't like it. The black-white theme looks much better and it would be noce if one could choose.

**Comment by MichalLebeda** [comment]
@flide can be closed now as new material design supports basic theming
