### ISSUE TITLE
Using emoji keyboard changes default keyboard

### ISSUE THREAD

**Issue by MichalLebeda** [8VIM/8VIM#171]
On my Samsung device, there is a problem when switching to emoji keyboard. The another keyboard is then set as default IM which is not what we want. This needs further investigation

**Comment by tzcrawford** [comment]
I have the same problem. Other keyboards do not have a button to easily change to another keyboard, so you have to go into the android settings menu every time you want to enter an emoji basically. My ignorant opinion is that it shouldn't be that difficult to include an emoji menu in 8vim.

**Comment by flide** [comment]
It's actually pretty easy to include a emoji menu and it was, but it
increased the apk  size a lot (100+ mb), so I decided to seperate out the
emoji keyboard, it's called pictograph and should be available on google
play store.

**Comment by MichalLebeda** [comment]
Solved this by enabling system wide keyboard button 
![Screenshot from 2021-04-30 14-47-33](https://user-images.githubusercontent.com/5246963/116697110-13c00400-a9c3-11eb-8dab-9a4939115760.png)

**Comment by flide** [comment]
@tzcrawford does this solve the issue you were referring to?

**Comment by MichalLebeda** [comment]
It is a workaround allowing you to switch keyboards anytime

**Comment by tzcrawford** [comment]
@MichalLebeda @flide
> Solved this by enabling system wide keyboard button

> @tzcrawford does this solve the issue you were referring to?

Unfortunately, no, I think. I'm using a Samsung S7 Active with Android 8.0.0, and it appears that Samsung automatically resets to their default keyboard with their own version whenever you press the emoji button on 8vim or the keyboard button on Pictograph. I don't think this device has an option for enabling a system-wide keyboard button; plus this device replaces the "action bar" with physical buttons in this case. So I think the only way to quickly change keyboard is by going into the settings menu.

This device is the "Locked Down" version so it is not possible to disable or remove the Samsung keyboard without flashing over the OS, and I think this model of hardware made that problematic for some reason (at least at one point in time). We love Samsung 👏👏👏. I'd say this is a rare case and any fault is probably on Samsung.

**Comment by analpi** [comment]
Same issue here, also Samsung.
