### ISSUE TITLE
Librem 5/Pinephone/Desktop Linux port?

### ISSUE THREAD

**Issue by tzcrawford** [8VIM/8VIM#175]
I was wondering if there were plans to port 8vim to this platform now that the phones are starting to become more available. How difficult would this be to implement?

**Comment by flide** [comment]
never looked into it. not really sure.

**Comment by MichalLebeda** [comment]
it would mean "rewrite from scratch" as this is a java android app.

**Comment by flide** [comment]
Well... that mean no plans of that happening anytime soon.
