### ISSUE TITLE
Video Demonstration of similar keyboard (look here)

### ISSUE THREAD

**Issue by esmoak** [8VIM/8VIM#18]
This is a publicly available video of potential speed that can be obtained as shown on the old 8pen keyboard.

This is not me in the video.

Putting this here to help others get an idea about potential. 

https://youtu.be/tFNCiOVks2w

**Comment by geofrey** [comment]
We've come full circle. VI8 literally exists to recreate 8pen after the creator blackholed it.

**Comment by flide** [comment]
For now it is true that the keyboard is a drop in replacement for 8pen. I
hope this keyboard can do much more and better.

**Comment by esmoak** [comment]
Feel free to close this issue if you don't want it cluttering the issue tracker.

Just wanted to show others who are curious a real example.

Also, the 8pen game you linked in your readme doesn't exist anymore

**Comment by flide** [comment]
It's a shame, I think making a game to enhance the learning experience would be the next logical step for this keyboard.

**Comment by CaptainBlagbird** [comment]
It's still available if you click the link in the play store directly on your phone. However it I can only play level 1-4, for level 5 no letters start to  appear (at least on my phone).

Yea it's a shame, I really like the game for practising when 8pen was still around. It was a good learning curve starting with the easy letters and then gradually increasing and adding more letters.

**Comment by flide** [comment]
Since this issue was started to show a video demo for 8pen, is someone interested in making a demo video for 8vim that can be uploaded to play stores (f-droid and g-play)?

**Comment by JonnyHaystack** [comment]
Yeah, this keyboard seems really interesting to me, but I have to idea how to use it. The readme seems to explain everything except how to actually type letters.

**Comment by flide** [comment]
@JonnyHaystack 
https://www.youtube.com/watch?v=99vsUF4NuLk

**Comment by elig0n** [comment]
we need better quality video
also that keyboard looks a little prettier than the current 8vim

**Comment by flide** [comment]
8Vim is not pretty?... 😥

I am hurt ...😞

**Comment by elig0n** [comment]
sorry but the colors and alignment of the circle are simply better on 8pen :-) at least you get a chance to improve it though
