### ISSUE TITLE
Pressing enter sends message even if I have set up the app to not do that

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [8VIM/8VIM#188]
It even happens when the text box is empty

This feature should be removed altogether, it's only annoying

EDIT: Apparently it only happens in Discord?

**Comment by npostavs** [comment]
Do other keyboard not do this with the Discord app (I never use that myself)?

I guess [`MainInputMethodService.commitImeOptionsBasedEnter`](https://github.com/flide/8VIM/blob/iteration-7/8vim/src/main/java/inc/flide/vim8/MainInputMethodService.java#L300-L319) is relevant. Possibly replacing `sendDownAndUpKeyEvent(KeyEvent.KEYCODE_ENTER, 0)` with `sendText("\n")` could help. Similar to #174, but I didn't touch enter behaviour there.

**Comment by Lilith-In-Starlight** [comment]
It does not happen with other keyboards, only this one

**Comment by flide** [comment]
Can you name the app in which this issue is manifesting and how to
reproduce it?

**Comment by Lilith-In-Starlight** [comment]
The app is Discord

How to reproduce: Focus on the message bar, and press enter. You don't even have to have typed anything. Pressing enter is enough to cause this bug.

**Comment by flide** [comment]
I was not able to successfully reproduce this issue. Can someone else confirm this?

**Comment by ascpial** [comment]
To be more precise:
- type a message in the Discord message input
- press enter to go to a new line
- the message is sent

In other apps (for example OpenBoard), a new line is added and the message is not sent.

Here is a video showcasing the bug, and the behavior of OpenBoard:


https://github.com/8VIM/8VIM/assets/72463129/919892dc-19c6-4322-ab97-27dff9e04fc4

**Comment by BeeFox-sys** [comment]
i can confirm this is still happening, however this might be due to using an old version of discord.
