### ISSUE TITLE
Gestures and ... emoji's keyboard

### ISSUE THREAD

**Issue by giluriel** [8VIM/8VIM#189]
Hi,
(Still very excited after @adamschmalhofer help with hebrew layout. getting back to 8vim :)))

Two issues regarding usage of 8Vim:
1. The old 8Pen supported gestures. If I recall correctly, making half a circle  beneath the 8vim's letters, from left to right - typed in a smile emoji. very convenient :)  (having the ability to assign the gesture to specific emoji will be even nicer)
2. The emoji keyboard icon in 8Vim does not switch keyboard to emoji. instead it bring back the old keyboard. The 1st option in the setting on 8Vim is actually "select emoji keyboard" but it shows no emoji keyboard. only the regular ones.
can anyone point me to a keyboard that is "emoji" one? (android) or maybe it misses some additional command so it will launch the selected keyboard in emoji mode?

TNX

**Comment by adaschma** [comment]
Ok, you already noticed that I have been playing around with (1). Now I got around to publishing a prerelease. So you can try it out (and tell me what you think) https://github.com/adamschmalhofer/8VIM/releases/tag/hebrew-3 and https://github.com/adamschmalhofer/8VIM/releases/tag/german-3 (for English and German typeers).
