### ISSUE TITLE
Gesture for Repeating letters

### ISSUE THREAD

**Issue by Classifiedjunkie** [8VIM/8VIM#190]
When writing words like "Aggression" or "Successful" you the gesture for the two repeating letters can be time-consuming and tiring. 

My suggestion is that there be something of a quick double tap, or some other gesture that will allow you to repeat the letter you just typed. Another good suggestion would be to condense the symbols and the clipboard icon into some form of "Mode" icon and use the left sector icon with this repeating letters feature.

**Comment by flide** [comment]
unsure if leaving the flow of the word to tap on something is more efficient just to add a repeat character....
