### ISSUE TITLE
How do i input accents?

### ISSUE THREAD

**Issue by legacychimera247** [8VIM/8VIM#219]
Hello, i guess the title pretty much says all, ho do i input accents?for letters like è à ó and so on

And in case they are missing couldn't they be implemented?

**Comment by adaschma** [comment]
The currently released version only offers entering the Esperanto diacritics (ŭĥĵĉŝĝ). The next version will allow to select a language and enter those accents/diacritics. If you don't want to wait you can try out the version at https://github.com/adamschmalhofer/8VIM/releases/tag/devel-1

**Comment by adaschma** [comment]
Duplicate of #159
