### ISSUE TITLE
Add Toki Pona keyboard layout

### ISSUE THREAD

**Issue by m-rey** [8VIM/8VIM#237]
I've been learning [Toki Pona](https://wikipedia.org/wiki/Toki_Pona), a very simple conlang, and would like to use the 8VIM keyboard to write Toki Ppona, using an optimized layout for it.

**Describe the solution you'd like**
I'd like to have and be able to have a Toki Pona optimized layout for 8VIM. Preferably directly selectable from within the app, but importing the xml layout file manually would also work. SwiftKey is one of the few keyboards offering support for toki pona. Adding support to 8VIM would make this project stand out even more.

 I'm open to submit a PR for this if I get some guidance on how to best generate the layout.
I'll be scraping Toki Pona text to generate a dataset to calculate word/char frequencies etc. I assume this will be needed to generate an optimized layout.

What steps would be needed to make this feature request happen? Are there any tools already available that could help?

**Comment by flide** [comment]
Can you draw and upload, what the layout for Toki Pona would look like?
