### ISSUE TITLE
"Select diacritics layout" yields empty list

### ISSUE THREAD

**Issue by ThomasAH** [8VIM/8VIM#238]
Iteration-8 from F-Droid or Google Play.
Fresh install on Google Pixel 4a running Android 11 (current LineageOS 18.1)

After installation (no other configuration done), enable 8Vim and click on "Select diacritics layout".
A popup dialog "Choose the diacritics [OK]" with no other entires appears, see screenshot.

See https://github.com/flide/8VIM/pull/194#issuecomment-1007444929 for context.
![Screenshot_20220107-161157_8Vim](https://user-images.githubusercontent.com/4928697/148564675-3a1f6dd4-c71a-4772-a756-30fa27595fcd.png)

**Comment by lxne** [comment]
Same for me.

Fairphone 4
Android 11
8Vim iteration-8

**Comment by flide** [comment]
Interestingly, same happens with me when I tried to install it from either
of the stores...

it's a possibility that since the files are packed inside raw folder, that
might not be the right way to distribute them.

**Comment by hagelschaden** [comment]
I have the same problem. I tried downloading the xml file and adding it manually, but when I do that I have an empty keyboard with no letters. Does anyone have an idea how to make it work?

**Comment by bonswouar** [comment]
Same problem on my OnePlus 5 with Lineage OS 18.1

I've also tried installing the apk directly from github and it didn't fix it, any workaround ? 

Edit : I ended up loading the xml file directly

**Comment by hagelschaden** [comment]
> Edit : I ended up loading the xml file directly 

How did you do that? When I downloaded the file from the raw folder on github and loaded it manually, my keyboard was just empty..

**Comment by bonswouar** [comment]
> How did you do that? When I downloaded the file from the raw folder on github and loaded it manually, my keyboard was just empty..

Well that's exactly what I did though :/ _(at first I didn't notice the change, but then found out about the accented characters going backwards)_

**Comment by adaschma** [comment]
> > Edit : I ended up loading the xml file directly
> 
> How did you do that? When I downloaded the file from the raw folder on github and loaded it manually, my keyboard was just empty..

I had the same problem initially. The problem was that my browser saved the file as an empty text file. After going through several hoops I got the ~25KB file with the ending .xml and got it to work.
