### ISSUE TITLE
Allow backtracking

### ISSUE THREAD

**Issue by ManDay** [8VIM/8VIM#239]
Backtracking, that is undoing sector crossings would allow to
 - undo an erroneous turn from one sector into another or
 - undo choosing the wrong sector to start with

without interrupting the input by lifting one's finger.

**Comment by geofrey** [comment]
Alternative: Make backtracks meaningful, e.g. gesture as far as the desired base character, and then change direction to access the accented/decorated variants of that character.

*I should probably catch up other issues' discussion around accented characters.*

**Comment by ManDay** [comment]
If I read https://github.com/flide/8VIM/issues/159#issuecomment-848730986 correctly, this is the current situation. I was not aware of this, partly because the F-Droid build comes without accents currently. I'm not sure how this can be reconciled generically with a way to *undo* turns without becoming terribly confusing.

Maybe we could establish that backtracking in the absense of "variants" (e.g. accented characters) undoes turns? That could be generalized to the point where we say that as soon as a backtrack does not match anything (think "variants of variants" by a 2nd backtrack were possible), it acts as "undo". However, this generalization seems to be half-baked as there would be no simple way to undo characters with variants.

**Comment by ManDay** [comment]
I reconsidered with that new information and I am no longer in favour of this. The current meaning of backtracking to access variants (or more generally nested topologies) is a much better choice in my opinion. In analogy to how 8Vim attempts to replicate a natural flow, a small mistake (i.e. entering the wrong sector) should be immediately amendable (#240) much like you'd amend writing cursive. Larger mistakes (i.e. turning into the wrong direction) on the other hand are analogous to partly writing a wrong letter; it necessarily comes with the penalty of explicit erasure.

I think the behaviour of backtracking when *no* variants match still needs to be defined (*ignore*?), but as far as I am concerned this FR should be rejected.

**Comment by flide** [comment]
@ManDay, You have arrived at the conclusion that I would have voted for. Thanks :)
