### ISSUE TITLE
Make sidebar configurable regarding which side it is displayed.

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#24]
The 'sidebar' on the main-keyboard should be configurable to be visible either on the left or right side of the x-board.

**Comment by flide** [comment]
The issue is partially fixed. Currently the keyboard view is not updated instantly as soon as the configuration changes. To view the changes, you need to either
1. switch the phone to landscape mode and back OR
2. switch to a different keyboard and back.

A different ticket will be raised for the bug, closing this issue.

**Comment by BruceMustache** [comment]
you should also add a o option to remove it

**Comment by flide** [comment]
It serves a lot of essential function and cannot be removed.

**Comment by BruceMustache** [comment]
The selection can be reached swiping from right to center the others buttons has alternativies also
Disabling side bar can centralize the center circle and make it more minimalistic, simple
Should not be the default but a option
