### ISSUE TITLE
Ignore 0-turns

### ISSUE THREAD

**Issue by ManDay** [8VIM/8VIM#240]
0-turns (i.e. move from the circle into a sector and directly back into the circle from the same sector) should be ignored if chosen so by the user (e.g. they don't want them to act as a means to pick suggestions, c.f. [issue #1](https://github.com/flide/8VIM/issues/1#issuecomment-720947462)) for consistency by two reasons:
 - A 0-turn might occur accidentally due to inaccurate input and in such case, the desired result ignores the 0-turn.
 - A 0-turn might be the result of backtracking correction after accidentally entering into the wrong sector (c.f. issue #239), in which case ignoring the 0-turn is also the correct choice.

**Comment by geofrey** [comment]
This is an easy mistake to make and I believe suppressing such a null gesture would improve flow.

**Comment by flide** [comment]
I think this is doable, will give it a try.
