### ISSUE TITLE
Prevent add-space after character insertion

### ISSUE THREAD

**Issue by Paperweb** [8VIM/8VIM#266]
**Issue**
When i go back into a word to correct it and insert a character, a space is automatically added after it on completion.

**Solution**
While the auto-space is useful, it should only happen when no other character is following the current cursor position.
- Add space by default on completion
- Don't add space when a character is present right after the cursor

**Describe alternatives you've considered**
No alternatives known to me. I just have to go along and delete the extra space.

**Comment by ThomasAH** [comment]
One one hand this sounds helpful, on the other hand this creates an inconsistent behaviour if you do not want to insert just a character, but a whole word.
You know that you can avoid the auto-space by ending your stroke outside the circle?

**Comment by bobrippling** [comment]
> You know that you can avoid the auto-space by ending your stroke outside the circle?

That's a nice tip, thanks!

**Comment by Paperweb** [comment]
> One one hand this sounds helpful, on the other hand this creates an inconsistent behaviour if you do not want to insert just a character, but a whole word. You know that you can avoid the auto-space by ending your stroke outside the circle?

Good point. And awesome tip, thank you !
There should be a manual for such things ― but maybe it is the WIP wiki?

**Comment by alterNERDtive** [comment]
> You know that you can avoid the auto-space by ending your stroke outside the circle?

Glad I read through the issues before submitting a new one, that works for me :)

**Comment by Derpford** [comment]
> You know that you can avoid the auto-space by ending your stroke outside the circle?

This is helpful, but honestly, I'd rather have a toggle to disable auto-space altogether. I only just found out about this style of keyboard, and while I'm still learning how to use it, I'd rather not have to deal with inputs I didn't want in the first place. (I don't like autocomplete either :P )

[Edit] It's also worth noting that ending outside the circle also triggers certain other gestures, such as tabbing between fields or moving the cursor, which makes this impractical in some apps--such as 8Vim's own options menu and test screen.

**Comment by alterNERDtive** [comment]
> [Edit] It's also worth noting that ending outside the circle also triggers certain other gestures, such as tabbing between fields or moving the cursor, which makes this impractical in some apps--such as 8Vim's own options menu and test screen.

That’s a bug; and a fix has been done and released, but isn’t showing up in F-Droid yet because F-Droid is as slow as usual.
