### ISSUE TITLE
What does the ctrl button do?

### ISSUE THREAD

**Issue by Hate9** [8VIM/8VIM#272]
**Describe the bug**
Nothing in the wiki, the main page, or (where it should be) the app seems to indicate what the "ctrl" button at the bottom left (by default) of the keyboard actually *does*. Why is it there? Does it have implemented functionality, or is it a holdover from a previously-implemented or unimplemented feature? I can't seem to find any answers here, so I figured I'd ask.

**Comment by flide** [comment]
Agreed, it should be removed. In my 7-8 years of use, I have not used it
more then 10 times.

**Comment by Hate9** [comment]
What does it actually do?

**Comment by flide** [comment]
In the older android system you could actually do ctrl+z style commands,
they no longer work.

**Comment by Hate9** [comment]
Ah. It's a shame they removed that. In that case, yeah, it aughtta be removed

**Comment by ThomasAH** [comment]
I use Ctrl on Android often, but only when opening a local terminal or when I ssh into another system, which happens often enough, e.g. yesterday.
But Termux offers its own Ctrl key, so I wouldn't mind if Ctrl gets removed from 8vim, especially as it doesn't work for me, at least not with Termux.

**Comment by flide** [comment]
So, what we are looking for is a replacement for ctrl, but it being there is not really an issue. Going to close this issue for now and will wait for a light bulb to turn on.

**Comment by theFox6** [comment]
The ctrl button on other virtual keyboards does work on my phone and does things as you would expect. Such as ctrl+a (select everything), ctrl+x (cut), etc.
On 8Vim the ctrl button allows moving the caret by whole words and deleting whole words.
However it seems that selecting a letter when ctrl is enabled only types the letter instead of sending ctrl as modifier.
