### ISSUE TITLE
Backspace does not work properely in markdown editor

### ISSUE THREAD

**Issue by legion151** [8VIM/8VIM#273]
I am using hedgedoc as an editor for markdown. 

when i create a checklist i sometimes cannot use backspace at all. 
sometimes i can delete text but not the markdowncodes.
forward deleting works however.

if i switch keyboard to default it works as expected, so i assume it has sth. to do with 8vim. are there different keycodes involved?

thx for this awesome app.

**Comment by flide** [comment]
I will make a check

**Comment by flide** [comment]
couldn't find the 'hedgedoc' application, and was not able to replicate the same issue anywhere else.

**Comment by legion151** [comment]
https://pad.hackzogtum-coburg.de/HN8-5JmaQMyv87Cj8sr9bQ?edit

is an example. 

also just noticed that i was not able to use backspace on youtube in a browser on a laptop using kdeconnect.
