### ISSUE TITLE
Small empty box when typing key from number/special keyboard

### ISSUE THREAD

**Issue by falzonv** [8VIM/8VIM#274]
Hello,

First of all thank you very much for making this app!
I discovered it a couple of days ago and really like it, very interesting concept :-)

**Describe the bug**
When typing a key from the "number / special characters" keyboard, a small box is displayed for a short duration (like for letter-preview) but it is always empty.
This box should either display the typed character inside, or not appear as it currently looks like a glitch.

**To Reproduce**
1. Go to the "number / special characters" keyboard
2. Click on any character (number, special character, also delete and enter keys)
3. A small box (like for letter-preview) is displayed but it is empty

**Expected behavior**
This box should either display the typed character inside, or not appear as it currently looks like a glitch.
If the box is removed, a way to provide feedback that a key is being pressed could be to color the background of that key (with light gray for example) and set it back to the original color when the key is released.

**Screenshots**
To make this screenshot I continuously pressed the "&" key, we see that the preview(?) box is empty.
*(Don't pay attention to the sound panel, it popped each time I tried to retake the screenshot.)*
<img width="50%" src="https://user-images.githubusercontent.com/4698531/169691326-c5297629-bf69-4c41-92ec-8dbc69d932c1.png"/>

**Smartphone**
 - Device: Motorola X4
 - OS: Lineage OS 18.1 (Android 11)

**Comment by flide** [comment]
And here I thought I have removed all preview boxes already. Will look into it.

**Comment by falzonv** [comment]
Thank you for the fix!
