### ISSUE TITLE
Missing "ś" in polish diacritics layout

### ISSUE THREAD

**Issue by Dani3I** [8VIM/8VIM#278]
**Describe the bug**
All of polish diacritics are working (e.g. for the letter "ź" I move my finger to the section that would correspond to the letter "z", but then (before moving to the center) I move my finger one section earlier and then I move my finger to the center (the exception is the letter "ż" for which I have to move my finger two sections earlier and then to  the center), except for "ś" (the "ś" letter does not appear).

**To Reproduce**
1. Select "Polish"diacritics layout.
2. Hold your finger on the screen from the center...
3. ...move your finger to the top section...
4. ...move your finger to the left section...
5. ...move your finger to the top section...
6. ...move your finger to the center...
7. ...release your finger from the screen.
8. Notice that the letter "ś" does not appear.

**Expected behavior**
The letter "ś" should appear.

**Smartphone (please complete the following information):**
 - OS: Android 11

**Additional context**
App version: 8Vim "iteration 9" from F-Droid

**Comment by Dani3I** [comment]
As it turned out my issue is sort of fixed:
The commit to add polish "ś" was added even before I created my issue (commit in 2022.03.23 and I created this issue in 2022.06.25: https://github.com/flide/8VIM/commit/52b8d7f71443da3a2601eea55ece1080059ec2b5 (thanks to @jarmuszz )) and I discovered that only because I was wondering if this project is dead and this is for now as far as I understand iterally last commit which was made (it is showed just below "Go to file" button on main 8vim github page).

So I guess it will be fixed in next version (if it will be released because this project looks kinda abandoned - dead link to [www.8vim.com/](https://www.8vim.com/) on main github page and dead link to "Matrix" chat in app and last commit was in 2022.03.23 as I wrote), but for now it is possible to fix polish diacritics manually:
1. go to https://github.com/flide/8VIM ;
2. if on mobile view of website: click on "View code"; if you are on desktop: skip to "3.";
3. click on folders in order: "8vim" -> "src" -> "main" -> "res" -> "raw" and then click on file "pl_regular_polish.xml" (https://github.com/flide/8VIM/blob/master/8vim/src/main/res/raw/pl_regular_polish.xml);
4. depending:
4.1. if on desktop: click on "raw" button (https://raw.githubusercontent.com/flide/8VIM/master/8vim/src/main/res/raw/pl_regular_polish.xml), then click right mouse button, and then "save website as" (or something similar); after that move file to your mobile device storage;
4.2. if on mobile: click on three dots (next to info about number of lines and size of file) and click and hold on "View raw" until menu pops up, after that click on "download link" (or something similar) and optionally move the file to the directory you want;
5. Open 8vim app on your mobile device, then click on "Select layout file from device" and then find downloaded file ("pl_regular_polish.xml") and choose it (after that polish diacritics should be fixed).

**Comment by flide** [comment]
I will make a release soon.
Closing this issue.
