### ISSUE TITLE
Change currency symbol on first page of number/symbol pad

### ISSUE THREAD

**Issue by ThomasAH** [8VIM/8VIM#279]
**Is your feature request related to a problem? Please describe.**
I'm in Germany, so the currency symbol that I most often use is € (Euro), but the number/symbol pad has the ₹ (Rupee) sign on the first page. To reach the € (Euro) sign I have to switch to the second page, which interrupts input of e.g. price calculations:
123.45€ * 6 = 740.70€ (all numbers/symbols except for the € sign are on the first page)

**Describe the solution you'd like**
I'd like to have the € (Euro) sign on the first page of the number/symbol pad.
Obviously this isn't the best choice for everyone, so this should be configurable or automatically selected from the system locale.
The ₹ (Rupee) sign can then move to the second page, though I probably never need it except for writing this feature request.

**Describe alternatives you've considered**
1. Allow writing numbers via the main keybopard, as the € sign can already by written there with an adjusted diacritics layout file.
2. Allow adjustments to the number/symbol pad via a mechanism similar to the diacritics layout file.

**Additional context**
This came up in discussions #90 (German Layout)
The configured locale/language list on my phone is:
1. English (Germany) - to have English as the main language, but German date format and currency symbol €
2. English (United States) - because some apps don't know en_DE and would otherwise fall back to de_DE
3. Deutsch (Deutschland) - if I want to use German language/locale

page 1: <img src="https://user-images.githubusercontent.com/4928697/184311621-0c61cc79-a437-4143-ad99-b3727a1bdfb6.png" width="270"> page 2: <img src="https://user-images.githubusercontent.com/4928697/184311643-f0501049-0969-43fc-a2bc-c1d6fb39c125.png" width="270">

**Comment by martin-braun** [comment]
The German layout allows you to insert € with DOWN-LEFT-DOWN.
