### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by mitexleo** [8VIM/8VIM#281]
Not seeing any receny commits .. Is is project dead?

**Comment by ThomasAH** [comment]
Doesn't look dead to me: There is active discussion about international and hacking layouts, with layout XML files available for download that you can import into the existing app, so no need for a new version until there is a consensus about how the layouts should look like.

**Comment by mitexleo** [comment]
> Doesn't look dead to me: There is active discussion about international and hacking layouts, with layout XML files available for download that you can import into the existing app, so no need for a new version until there is a consensus about how the layouts should look like.

Okay 👍  ... I'm sorry 😞... I didn't notice that ..
