### ISSUE TITLE
F-Droid version over 1 year old?

### ISSUE THREAD

**Issue by lxne** [8VIM/8VIM#289]
Hi,

after your policy issue I checked the 8Vim F-Droid version. Are you planing on updating it, too?

Best wishes
Alex

**Comment by flide** [comment]
Well... isn't it suppose to get picked up automatically as long as I keep the fastlane folder updated and the tag in line with the versionName?

**Comment by lxne** [comment]
> Well... isn't it suppose to get picked up automatically as long as I keep the fastlane folder updated and the tag in line with the versionName?

I am not sure, but we'll see.
Probably you are right.
Thank you.
