### ISSUE TITLE
Setup automated deployment 

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#291]
**Is your feature request related to a problem? Please describe.**
It's too much of an effort to deploy 8vim. Also, since it requires effort, I try to release when a lot of changes have piled on. The deployments should be seamless and frequent so the changes get to the end user as soon as possible.

**Describe the solution you'd like**
Setup fastlane as a deployment solution and use github actions to deploy on every merge to master.

**Comment by flide** [comment]
I am now able to deploy to playstore in a single command. I will consider this closed for now.

**Comment by martin-braun** [comment]
@flide Could you please continue to deploy to GitHub, so we can fetch and install your keyboard using https://github.com/ImranR98/Obtainium?
