### ISSUE TITLE
Feature: Update the keyboard to support multiple layers

### ISSUE THREAD

**Issue by MaethorNaur** [8VIM/8VIM#292]
**Is your feature request related to a problem? Please describe.**

Currently, the keyboard only supports one layer, it would be nice to display other layers (depending on the language)

I already try that feature, here in action:

![output](https://user-images.githubusercontent.com/25067710/230611791-fd900c1c-207b-4ba9-af8d-85ab674a85dd.gif)

However, it requires updating the XML definitions.

Changes can be found [here](https://github.com/MaethorNaur/8VIM/tree/higlight-diatrics)

**Comment by flide** [comment]
Can you raise a PR...
![giphy.gif](https://user-images.githubusercontent.com/7330631/231047205-0586bc4d-6414-4516-993d-5344b81b45a2.gif)

**Comment by MaethorNaur** [comment]
PR raised :)

**Comment by zen0bit** [comment]
Í oÓ nÓ

**Comment by MaethorNaur** [comment]
I also created a version using YAML instead of XML: MaethorNaur/8VIM#2
