### ISSUE TITLE
Selection Mode doesn't work in the Obsidian App

### ISSUE THREAD

**Issue by denizonm** [8VIM/8VIM#293]
**Describe the bug**
Selection Mode doesn't work in the Obsidian App.

**To Reproduce**
1. Go to the obsidian app
2. Try to select text using either the swipe gesture or the selection screen.

**Expected behavior**
The text is selected.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Graphene OS

**Comment by flide** [comment]
So selection in 8vim is a hack, to select we send out 'shift + arrow key code' hence emulating selection. it's possible not all apps honor that. 

Need to find a better selection process.

**Comment by denizonm** [comment]
I see, thank you. If it makes any difference, i can select stuff when i press "shift + arrow key" from a physical bluetooth keyboard (in obsidian android).
