### ISSUE TITLE
The turkish diacritics don't work

### ISSUE THREAD

**Issue by denizonm** [8VIM/8VIM#294]
**Describe the bug**
The Turkish diacritics scheme doesn't produce any of the characters

**To Reproduce**
(to give the "ç" character as an example)
1. swipe left, starting from the circle
2. make a upward half circle to the right
3. move to the top, then re-enter the circle
4. nothing happens.

**Expected behavior**
Turkish characters appear when diacritics commands are entered.

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Graphene OS

**Additional context**
Maybe it is my misunderstanding, but i can make the "ç" character with the french keyboard, but the same gesture doesn't create it in the Turkish diacritics setting

**Comment by flide** [comment]
It seems to be working fine.

The sequence is as follows : 
circle -> left -> top -> right -> top -> right -> circle
