### ISSUE TITLE
Support clipboard manager

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#3]
Since 8Vim has a paste functionality already, it would be really good if a full clipboard manager can be supported from the keyboard directly.

I am unsure about how this functionality should be accessed. Any suggestions are welcome.

**Comment by reacherjack422** [comment]
I would suggest putting the icon in the cut/paste panel accessed with the middle 4 arrow icon from the side bar.

A possible gesture would be to swipe from the top quadrant through the middle circle to the bottom quadrant

**Comment by flide** [comment]
Certain requirements need to be satisfied for this to be considered complete. 

- any text copied on the os clipboard should be available in the clippad
- The number of previous clips to be kept before the oldest one gets deleted should be user configurable. 
- user should be able to pin any clippings to keep them available forever. 
- user should have the ability to delete any cliping.
- the clippad should be easily accessible, it can either be accessible from the sidebar like the selection keypad and/or the - gesture "left -> circle -> hold" can act as an extension to the paste functionality and open up the clippad.

**Comment by flide** [comment]
Can see implementation of clippad features in the following keyboards available on playstore :

- [Clipkey](https://play.google.com/store/apps/details?id=com.cotedia.clipkey)
- [Xploree](https://play.google.com/store/apps/details?id=com.kpt.xploree.app)

**Comment by martin-braun** [comment]
"A possible gesture would be to swipe from the top quadrant through the middle circle to the bottom quadrant" - It would be nice not to introduce new maps, this prints a `|` for me, already.
