### ISSUE TITLE
How to debug my custom layout?

### ISSUE THREAD

**Issue by MaxGyver83** [8VIM/8VIM#300]
**Describe the bug**

I have created a new layout using [8vim_keyboard_layout_calculator](https://github.com/Glitchy-Tozier/8vim_keyboard_layout_calculator) and created a new xml file by copying and updating an existing file manually.

For the first iterations, it worked. After some more changes, I got an empty keyboard.

How can I debug my layout?

(I know that this feature is experimental.)

**To Reproduce**
1. Go to 'Settigns -> General'
2. Click on 'Select layout file from device'
3. Pick '[de_german_english_80_20.txt](https://github.com/flide/8VIM/files/11254919/de_german_english_80_20.txt)' (rename to xml)
4. See empty keyboard layout

**Expected behavior**
No empty keyboard layout.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord 2
 - OS: Android

**Additional context**

**Comment by MaxGyver83** [comment]
I just built the project in Android Studio and ran in on my smartphone. The debug output in Android Studio pointed me to the error in my configuration:

In one place I wrote `DOWN` instead of `BOTTOM` 🙃

**Comment by MaxGyver83** [comment]
It looks like #301 would have prevented this error.

But nevertheless, an error message would be nice, no matter how the keyboard layout xml file looks like.

**Comment by MaethorNaur** [comment]
Yes, I agree the UI could be improved.
Currently, if the layout is not properly loaded, the keyboard is not rendered properly.
Maybe we might create another issue for that and discuss the behaviour. (toast, defaulting to a default layout, ...)

**Comment by martin-braun** [comment]
@MaethorNaur Default layout will not help to figure out the cause. Right now the only thing to approach this quickly is to remove stuff until it works to track down the issue. 

I think a toast from any exception in the TOML parser will help, but it also needs a custom syntax parser to understand syntactically correct mistakes like typos in keys, etc.

**Comment by MaethorNaur** [comment]
I've created a PR #331 showing the file's error.
Also, it includes a JSON schema, which can be used to validate the file beforehand
