### ISSUE TITLE
Diacritics don't work properly

### ISSUE THREAD

**Issue by Alfika07** [8VIM/8VIM#305]
If using the Hungarian diacritic layout, it only writes "á" "é" "ó" and "ú" in upper case.

Note that it doesn't affect "ö" "ő" "ü" and "ű".

There is also no way of typing "í".

I'm using 8VIM iteration-11.

OS: MIUI 14.0.6.0.TKOEUXM

**Comment by jethrodawnfine** [comment]
In the Portuguese layout, all the "a"s are made in the opposite direction. While we should do the movement CENTER-RIGHT-TOP-RIGHT-CENTER to get "á", we actually need to do the movements as if we were trying to get "y" with diacritics. So it's working, but with the wrong movement, like CENTER-TOP-RIGHT-TOP-CENTER to get "á". And the same is happening if we want all the other "a" diacritics.

**Comment by Alfika07** [comment]
> In the Portuguese layout, all the "a"s are made in the opposite direction. While we should do the movement CENTER-RIGHT-TOP-RIGHT-CENTER to get "á", we actually need to do the movements as if we were trying to get "y" with diacritics. So it's working, but with the wrong movement, like CENTER-TOP-RIGHT-TOP-CENTER to get "á". And the same is happening if we want all the other "a" diacritics.

Just checked it.

Maybe it works in Portuguese but it doesn't work in Hungarian.

Also if it works like that in Portuguese is still an issue beacause CENTER-RIGHT-TOP-RIGHT-CENTER should be the right movement. CENTER-TOP-RIGHT-TOP-CENTER is not intuitive for "á" at all.

**Comment by jethrodawnfine** [comment]
> In the Portuguese layout, all the "a"s are made in the opposite direction. While we should do the movement CENTER-RIGHT-TOP-RIGHT-CENTER to get "á", we actually need to do the movements as if we were trying to get "y" with diacritics. So it's working, but with the wrong movement, like CENTER-TOP-RIGHT-TOP-CENTER to get "á". And the same is happening if we want all the other "a" diacritics.

In my case, the issue was solved with the last Iteration on PlayStore, which changed the steps to access the diacritics layouts.
