### ISSUE TITLE
Move backwards to go back in the chain?

### ISSUE THREAD

**Issue by AsafMah** [8VIM/8VIM#307]
**Is your feature request related to a problem? Please describe.**
Feature request - the keyboard is fun, but sometimes I miss a letter and "overturn", it sucks because then you have to delete and start over.

**Describe the solution you'd like**
When you go back to a quadrant (so if you started clockwise you'd go counterclockwise) it goes back in the selection, so if you were at "b" it goes back to "y" etc

I can probably implement it myself if needed

**Comment by flide** [comment]
I can understand the frustration. If it's just the characters it would have had made sense, but 8vim has a lot of nifty gestures and rely on the assumptions that the movement sequence will not be changed mid movement.
