### ISSUE TITLE
it just not types

### ISSUE THREAD

**Issue by MASTERdjango** [8VIM/8VIM#309]
**Describe the bug**
when I type no character gets out putted
this video has the data:
https://youtube.com/shorts/WHViyOfOOMQ?feature=share

**To Reproduce**
install the app
go a textbox 
type... fail

**Expected behavior**
to type characters

**Screenshots**
there is a video

 - Device: not going to tell but it is hardware enough.
 - OS: android 12

**Additional context**
apk freshly installed

**Comment by anoburn** [comment]
Take a look at the [video](https://www.youtube.com/watch?v=q3OuCR0EpGo) referenced in the readme for basic usage.
To select a letter, you have to return back to the circle in the middle. You can keep swiping until the word is finished, and only then lift your finger. This also adds a space behind what you just typed.
