### ISSUE TITLE
No more letters and language selection after last update

### ISSUE THREAD

**Issue by Sedathems** [8VIM/8VIM#311]
There are no letters visible after the update, and there is no input. Also the diacritics selection in the setup menu is empty.  
The cut and paste menu still works.

![Screenshot_20230530-112221](https://github.com/flide/8VIM/assets/135013955/3a868860-cd29-498a-995e-83ea2f994289)
![Screenshot_20230530-112229](https://github.com/flide/8VIM/assets/135013955/c8460798-94e7-4a30-977f-320e3e4be730)

 

**Smartphone (please complete the following information):**
 - Device: fairphone 4
 - OS: android 12

**Comment by mtivi** [comment]
I am seeing the same issue on a Pixel 5. I'm using the beta stream from the play store.

**Comment by marcossmtp** [comment]
for me is the same samsung s7 with oreo

**Comment by Wjxfi** [comment]
Same, miui 13.0.5

**Comment by mapperr** [comment]
same here,
on one plus 7tpro and microg lineage android 12

**Comment by MaethorNaur** [comment]
CF: #312

Fixed on playstore. Not yet on F-droid.
In the meantime, I'm sharing the APK with the fix: https://drive.google.com/file/d/1PaUQ2-TtubsD3Z_PRE3YJT1q5rIwTAoS/view?usp=sharing

**Comment by supernatural30** [comment]
Why isn't the release in Github releases section?

**Comment by MaethorNaur** [comment]
Don't know. I'm also working on a github actions which should smooth releases (creating the changelog/release on github, pushing to google playstore/fdroid)

**Comment by MaethorNaur** [comment]
@urmomseksy 

> Why isn't the release in Github releases section?

After checking F-droid doc, the release is automated. It's based on tags.
There's no new tag for the bug fix, therefor no new version on F-droid is pushed

**Comment by marcossmtp** [comment]
So, if it's solved why is not the corrected version in f-droid?

**Comment by MaethorNaur** [comment]
As I wrote in the previous comment, @flide has to create a new tag/release note for F-droid to pick it up.
I'm sorry I cannot do more atm.

I'm working on new GitHub actions to automate the release and avoid having that kind of issue (I worked with the debug build, but the release build removed some code that led to that bug).
Basically, the idea is to create a release artefact to test. Once that's OK, the release process can carry on.

**Comment by marcossmtp** [comment]
ok, thanks

**Comment by mtivi** [comment]
I am able to type again. I have however lost the ability to type the number zero. 

Screenshots for the two symbols pages on the default english layout:

![Screenshot_20230605-181139.png](https://github.com/flide/8VIM/assets/60046004/014189d5-8f9b-47f2-a4ff-24264076c34f)

![Screenshot_20230605-181249.png](https://github.com/flide/8VIM/assets/60046004/b43af557-b048-4983-b535-d8b2adbc6c9d)


I'm fairy certain there was a zero option before.

**Comment by MaethorNaur** [comment]
Thx. I'll have a look as soon as I'm back home. I'll probably create a PR in a few hours 🙂

**Comment by MaethorNaur** [comment]
@mtivi 
PR created: #314

**Comment by flide** [comment]
Duplicate for #312
