### ISSUE TITLE
iteration 12 is broken when installed using google playstore

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#312]
**Describe the bug**
iteration 12 is broken when installed using google playstore

**To Reproduce**
1. Go to playstore
2. search and install 8vim
3. enable 8vim and switch to it
4. it's a blank layout, is unresponsive and the layout list is blanked out as well

**Expected behavior**
A working keyboard

**Desktop (please complete the following information):**
 - Version : iteration-12

**Comment by MaethorNaur** [comment]
I'm having a look. It might be caused by the minification

**Comment by flide** [comment]
Not working @MaethorNaur

**Comment by martin-braun** [comment]
It broke everything.

![image](https://github.com/flide/8VIM/assets/24259245/ce65a3b5-9e2b-4ec9-a8aa-ea4283b81f82)

Nothing is working anymore, can't use 8vim ... @MaethorNaur Would be nice if you could fix it asap. Love the keyboard. If it takes longer, please let us know, so we can downgrade.

**Comment by flide** [comment]
it's fixed now, you should see iteration-12.2 on the playstore now.

**Comment by MaethorNaur** [comment]
Yes, we are aware about that. A fix has been released.

**Comment by MaethorNaur** [comment]
Quicker than me 😅

**Comment by siiky** [comment]
Hi, I just installed `12.12` from F-Droid and I seem to have this problem too, can't type anything. You say you've just released `12.2`, which I'd guess is `<12.12`, so is it a different problem, or are version numbers different on F-Droid?

~~I'll downgrade in the meantime.~~ Welp, for some reason it's giving me an "Invalid or corrupted APK" error when I try to install the previous version, weird...

**Comment by flide** [comment]
Yes, fdroid still needs to be updated

**Comment by martin-braun** [comment]
Glad you react so fast. Unfortunately, no Play Store here, I depend on F-Droid as well. Hopefully you can push the release without much delay. Thanks. :)

**Comment by MaethorNaur** [comment]
For those who are using F-droid, I'm sharing the APK with the fix:
https://drive.google.com/file/d/1PaUQ2-TtubsD3Z_PRE3YJT1q5rIwTAoS/view?usp=sharing

**Comment by atlasveldine** [comment]
Why is this being shared via Google Drive and not just built and released via GitHub? I'm also on F-droid and obviously it's still broken, but, I can't even find a changelog to see what has even been changed, since build 11 is the latest visible in this repo. What's up with that? :/

> For those who are using F-droid, I'm sharing the APK with the fix: https://drive.google.com/file/d/1PaUQ2-TtubsD3Z_PRE3YJT1q5rIwTAoS/view?usp=sharing

Edit: Nevermind, still no tablet landscape mode, unusable for me. :(

**Comment by MaethorNaur** [comment]
I shared the apk until a new version is available via f-droid.
I'm also working on new release workflow

**Comment by MaethorNaur** [comment]
> Why is this being shared via Google Drive and not just built and released via GitHub? I'm also on F-droid and obviously it's still broken, but, I can't even find a changelog to see what has even been changed, since build 11 is the latest visible in this repo. What's up with that? :/
> 
> > For those who are using F-droid, I'm sharing the APK with the fix: https://drive.google.com/file/d/1PaUQ2-TtubsD3Z_PRE3YJT1q5rIwTAoS/view?usp=sharing
> 
> Edit: Nevermind, still no tablet landscape mode, unusable for me. :(

I'll have a look on the tablet landscape mode afterward ☺️

**Comment by kjoetom** [comment]
> For those who are using F-droid, I'm sharing the APK with the fix: https://drive.google.com/file/d/1PaUQ2-TtubsD3Z_PRE3YJT1q5rIwTAoS/view?usp=sharing

Thanks for sharing. I can confirm that the fixed version works again.
But unfortunately it seems not possible to load a custom layout file from device. When trying to do that, just nothing happens and the layout currently in place is kept unchanged.

**Comment by MaethorNaur** [comment]
If you are using an xml file it won't load. 
The format changed. There's a page on the wiki for that: https://github.com/flide/8VIM/wiki/Adding-a-new-language.

In the future, I'll see how to create a feedback if you are trying to load an incorrect file

**Comment by kjoetom** [comment]
Thanks for the quick reply. I hadn't noticed the format change until now, sorry about that.

**Comment by MaethorNaur** [comment]
No worries :).

Btw if there's anything which is not clear on that wiki page, you can give feedback (not always to make it clear when you are the one who developed the feature)

**Comment by martin-braun** [comment]
@MaethorNaur It would've been great to have a deprecation warning in advance, or perhaps a migration tool that converts the XML into YML.

**Comment by MaethorNaur** [comment]
Indeed, my bad. I'll try to work on a migration tool.

**Comment by martin-braun** [comment]
@MaethorNaur Thanks, could you please rebuild and publish iteration-11 on GitHub in the meantime? Release iteration-11 misses the old APK. I think a migration tool could be made quickly, but I'm very busy at the moment, so I'm glad that you will take care of that. 

However, in the meantime I'm stuck with the conventional keyboard, which is unfortunate. 

I'd like to downgrade for now.

**Comment by MaethorNaur** [comment]
Sorry, I can't rebuild the APK for releases :(

**Comment by martin-braun** [comment]
@MaethorNaur Yes, true, @flide could you please re-publish iteration-11 until we can migrate our layouts properly? The current release is nice in a sense that this app evolves, which is fantastic and refreshing, however the current iteration seems to be unstable and incompatible with existing custom layouts.

Thank you.

**Comment by MaethorNaur** [comment]
The previous release can be found there: https://f-droid.org/repo/inc.flide.vi8_11.apk

**Comment by martin-braun** [comment]
@MaethorNaur Thank you, I had no idea F-Droid allows downgrading, fantastic. Thank you for the effort in finding this. :) I hope you will have great success with the migration tool. A simple python script could already be sufficient if you ask me. 

For anybody else trying to downgrade without facing the downgrade failure issue: USB debugging and running `adb install -r -d inc.flide.vi8_11.apk` will allow to downgrade without uninstall.

**Comment by flide** [comment]
I have created a tag and pushed to github, hopefully f-droid would pick it up soon.

**Comment by flauta** [comment]
> If you are using an xml file it won't load. The format changed. There's a page on the wiki for that: https://github.com/flide/8VIM/wiki/Adding-a-new-language.

Does this mean that 8vim from now on can load (at runtime) custom layouts only in YAML format, OR that 8vim can use only the keyboards that are added to the source before compiling it? (and no more load custom layouts at runtime at all?)

**Comment by kjoetom** [comment]
I have just tried to convert my custom xml layout into a usable yaml layout using several online converters. Unfortunately, the result does not match the format described on the wiki page for the yaml described here: https://github.com/flide/8VIM/wiki/Adding-a-new-language.

**Comment by MaethorNaur** [comment]
> t 8vim from now

It means it can just load yaml file

**Comment by MaethorNaur** [comment]
> I have just tried to convert my custom xml layout into a usable yaml layout using several online converters. Unfortunately, the result does not match the format described on the wiki page for the yaml described here: https://github.com/flide/8VIM/wiki/Adding-a-new-language.

Yes the yaml is not a 1:1 of the XML.

The migration tool can be found: https://github.com/flide/8VIM/pull/316

**Comment by kjoetom** [comment]
Well, this sounds really interesting. However, I don't know how to use the migration tool (or is it supposed to migrate automatically in 8vim when importing an xml file).

Also: is it possible to use it to map movements like the following in the first layer?

![230750784-a05765b1-f413-44d3-9a59-e14ac71a73e2](https://github.com/flide/8VIM/assets/77550697/e7266b4f-77f7-4dbf-aff5-c661f0f889ac)

**Comment by MaethorNaur** [comment]
The migration is external from the app (it's a nodejs app). I created a readme under the migration folder. However, the migration tool is a best-effort one. You need to correct the yaml file

by default, the movement sequence is computed depending on its position. But if a movement_sequence is provided, it will ignore the computed one.

From the wiki: 

```
List of the finger position required to trigger this action. If this option is not defined, the movement sequence will be computed depending on the layer, sector, part and position of the action. Required for the hidden layer.
```

**Comment by flide** [comment]
Can someone confirm if the fdroid version is working as expected?

**Comment by MaethorNaur** [comment]
No it did picked up the last version

**Comment by MaethorNaur** [comment]
I think it didn't build it because of the missing changelogs file (`15.txt`)

**Comment by flide** [comment]
okay, let me update that.

**Comment by MaethorNaur** [comment]
Maybe create a new tag too (not sure if fdroid will pick it up since the metadata file has already been updated)

**Comment by MaethorNaur** [comment]
@kjoetom 

> Well, this sounds really interesting. However, I don't know how to use the migration tool (or is it supposed to migrate automatically in 8vim when importing an xml file).
> 
> Also: is it possible to use it to map movements like the following in the first layer?
> 
> ![230750784-a05765b1-f413-44d3-9a59-e14ac71a73e2](https://user-images.githubusercontent.com/77550697/244214038-e7266b4f-77f7-4dbf-aff5-c661f0f889ac.png)

Quick update I closed the PR and moved the tool to a different project: https://github.com/MaethorNaur/8vim-migration

To install the tool: 

```sh
npm install -g MaethorNaur/8vim-migration
```

To use it (displaying the help):

```
8vim-migration -h
```

**Comment by flide** [comment]
Iteration 13 has been released, should be available on playstore and f-droid in a few hours.

**Comment by marcossmtp** [comment]
2 days ago was announced Iteration 13 in 2 hours  and two days later I cant see it in google play or f-droid. What happenedm

**Comment by alterNERDtive** [comment]
I'm still not seeing 13 on fdroid, updating cache doesn't help. Is that a problem on my end?

**Comment by MaethorNaur** [comment]
No.
Apparently, it has been built yesterday on F-droid. Maybe it will be released tomorrow

**Comment by siiky** [comment]
New version is out on F-Droid and working. I was starting to lose my mind, I can't type on a QWERTY keyboard anymore...

**Comment by martin-braun** [comment]
Everything's good again, this can be closed I guess. :)

**Comment by flide** [comment]
app now available, closing issue
