### ISSUE TITLE
Missing number "0" on number-layout

### ISSUE THREAD

**Issue by henrikx** [8VIM/8VIM#318]
Not sure if I'm missing something obvious here, but I can't seem to find the number "0" on the number layout? I only see numbers 1-9

**Comment by henrikx** [comment]
Possible duplicate? https://github.com/flide/8VIM/issues/181

Makes an otherwise great keyboard completely unusable though. You can't have a keyboard without 0...

Is there any workaround?

**Comment by svent1nel** [comment]
You can still type the number 0 with the numpad if you press below the number 8, but you need to press very far down (on my phone, I have to press the very edge between 8vim and the switch keyboard bar). It does seem like a duplicate of #181 since the keyboard is getting cut off

**Comment by henrikx** [comment]
> You can still type the number 0 with the numpad if you press below the number 8, but you need to press very far down (on my phone, I have to press the very edge between 8vim and the switch keyboard bar). It does seem like a duplicate of #181 since the keyboard is getting cut off

I wish that worked on my phone, but no it is completely cut off with no way to access it. Oneplus 7 Pro.

**Comment by martin-braun** [comment]
This seem to be solved now.

**Comment by henrikx** [comment]
> This seem to be solved now.

where?

**Comment by flide** [comment]
I hope this is fixed with iteration 13

**Comment by martin-braun** [comment]
@henrikx I had the same issue and `iteration-13` solved it for me. Could you please update and respond?

**Comment by henrikx** [comment]
> @henrikx I had the same issue and `iteration-13` solved it for me. Could you please update and respond?

Where can I download iteration-13? The newest release on GitHub is iteration-11.

**Comment by henrikx** [comment]
Nevermind, it was available as an update on Google Play. Seems to be solved now :)
