### ISSUE TITLE
layout switch gesture documentation

### ISSUE THREAD

**Issue by flauta** [8VIM/8VIM#320]
I can't find anywhere (wiki, source) how to activate the secondary layers.
The "Usability guide" Wiki page is incomplete and there isn't the text and/or animation to show this movement.

Only in the F-Droid app page I read the sentence " Multiple Layers for layouts: accessible through the gesture - bottom-> centre -> bottom. Cycle clockwise to see all 5 extra layers if available."

Actually, to get the symbols in second layer the gesture I need is always bottom-center-bottom-center. For the third: bottom-center-bottom-left-center. And so on. 

Since the layer switch happens after the bottom-center-bottom gesture AND many second-layer symbols are located in the bottom area, I think it's important to explain that B-C-B gesture is not sufficient to get the symbols without before returning to center.

I don't know if this is the desired behaviour; personally I find a bit confusing the fact that the 2L-symbols that appear after the BCB gesture don't work if selected before returning to C.

**Comment by flauta** [comment]
After reading the messages in the 8vim Matrix lobby, I close this and wait. Nice and useful work.

**Comment by cyphersnake** [comment]
At least leave a link. I've encountered the same problem and I still don't understand how to switch to the next layers, after the first one and is it possible to switch to the layer on a permanent basis (as from the local language to English), etc.
