### ISSUE TITLE
No diacriptics in spanish layout

### ISSUE THREAD

**Issue by marcossmtp** [8VIM/8VIM#321]
After update to iteration 13 from 11 it stops to works the gestures to enter diacriptics in spanish layout. I can't enter ñ or áéíóú, I can see that now when you select spanish it appears that you have 2 layouts, but with the BCB appears the second layer with ñ € , ¿ and  ¡. Idont know which is the sense of that layout. Anycase when you select spanish layout diacripts cant be used.
/

**Comment by MaethorNaur** [comment]
Yes, indeed I forgot `áéíóú`. Let me fix that.

Otherwise, I can enter: `ñ`.

[device-2023-06-09-235438.webm](https://github.com/flide/8VIM/assets/25067710/dd802892-00be-4f28-8ef0-7cb5cb3866e7)

**Comment by MaethorNaur** [comment]
Fix available in that PR: #322.

Meanwhile, you can download the layout and use it as a custom one: https://github.com/flide/8VIM/blob/01604854294e1be5497c9c4a620dde8a16e235af/8vim/src/main/res/raw/es.yaml

Also I've updated the WIKI for the layers: https://github.com/flide/8VIM/wiki/Usability-Guide#layers

**Comment by marcossmtp** [comment]
The method to enter ñ is to slow, using the second layout. Is really missed the old method to enter diacriptics of go over and return to enter the diacriptic? , it was the fastest method to enter a diacriptic. The new method is really slow. Have more than one layout and navigate over them is a great idea and use YAML to configure too, but it would be nice have the two methods, for me as I said is too much fast the old method to enter diacriptics.
And in spanish exist the diacriptic ü too, not very used but necesary for a lot of words.
And a good feature it would be can add several layouts from files and can select them from a menu.
Thanks

**Comment by MaethorNaur** [comment]
`ü` is also available on the 3rd layer

**Comment by marcossmtp** [comment]
so, it's no possible to have the old method to use diacriptics?. or a option to enable?
To write ñ I need to do 5 gestures, in old method I need to do only 3.
Any case I edit the yaml file to add ü, in spanish are only two layouts and in the second layer I dont know how to select the letter. 
I insist that to have serveral layouts are a great idea for a lot of symbols or to have the option to edit your personal layouts , thats great.
But for diacriptics that are used like in spanish although in every word is too slow to change layout every time. Mantain the old method too I think it would increase a lot write speed.

**Comment by kjoetom** [comment]
... it is the same situation with the German layout.

Since diacritics and capital letters are so common that they occur multiple times in almost every sentence, the new method of entering them is way too slow, since 8vim also lacks auto-completion (which I do not care about, by the way).

Can we combine the old method with the new one?

**Comment by MaethorNaur** [comment]
Yes, it's possible to map to the old movements.

I'll update the layouts 👍🏾

**Comment by kjoetom** [comment]
Great - thank you. 
By the way, if I can see how such an extended layout looks correctly in yaml format, I can then also create my own layout again and use it in the current 8vim. That would be great, of course.

**Comment by MaethorNaur** [comment]
> Great - thank you. By the way, if I can see how such an extended layout looks correctly in yaml format, I can then also create my own layout again and use it in the current 8vim. That would be great, of course.

You're welcome. Do you mean in the wiki? otherwise, you can have a look at `special_core_gestures.yaml` or `fr.yaml`

**Comment by MaethorNaur** [comment]
I'll update 8vim to support both custom movements and layers one ;)

**Comment by kjoetom** [comment]
> You're welcome. Do you mean in the wiki? otherwise, you can have a look at `special_core_gestures.yaml` or `fr.yaml`

Thank you for pointing this out. I'll definitely take a look at that in the next few days.

**Comment by MaethorNaur** [comment]
👍🏾

**Comment by marcossmtp** [comment]
Thats great to heard,  It would be nice that it would be nice to have the method to configure layouts with gestures in the wiki. 
Thanks

**Comment by MaethorNaur** [comment]
In the wiki, it's stated you can provide `movement_sequences` object. This value will be used instead of the computed one.
The change I'm making will allow having the "slow" method with a custom one (if provided) on other layers.

**Comment by marcossmtp** [comment]
oh ok, thanks that's great
But is possible in the a personal yaml include that gestures?
I cant find special_core_gestures.yaml to see how can I do it sorry.
And is possible to add more than on layout from a file and have them in the list of layouts and have the ability of select and delete them?

**Comment by MaethorNaur** [comment]
> oh ok, thanks that's great But is possible in the a personal yaml include that gestures? I cant find special_core_gestures.yaml to see how can I do it sorry. And is possible to add more than on layout from a file and have them in the list of layouts and have the ability of select and delete them?

Yes ofc. For instance:

```yaml
  extra_layers:
    first:
      sectors:
        bottom:
          parts:
            right:
              - lower_case: ö
                movement_sequence:
                  - inside_circle
                  - bottom
                  - right
                  - bottom
                  - inside_circle
```

Here is the link to the file: https://github.com/flide/8VIM/blob/master/8vim/src/main/res/raw/special_core_gestures.yaml

**Comment by MaethorNaur** [comment]
I'm re-adding the old movements for all languages. Fun (well that's on me 😅)

**Comment by marcossmtp** [comment]
thanks very much for your work.

**Comment by MaethorNaur** [comment]
No worries

**Comment by MaethorNaur** [comment]
I've updated the PR.
In that change `movement_sequence` will replace the computed movement like before.
However, I added new "quick" movements for the letters. The "slow" movements are still available

Here is an example.
![layers](https://github.com/flide/8VIM/assets/25067710/64475dd4-fc85-4b2b-976f-dda50c31e909)

It might change some movements for some languages but it should be faster to type

**Comment by MaethorNaur** [comment]
For those you want to try that out, I've shared a debug build: https://matrix.to/#/!moWaJbLuMpOPkpYeeF:matrix.org/$for59CzZRkF6FPAE3Rb8ctKSKjQUJt3kQ4NqyozS1kY?via=matrix.org&via=tchncs.de&via=cadence.moe

**Comment by marcossmtp** [comment]
Oh very nice. Is all programmed in the yaml file?
When I try to program in the layout file the movement_sequence in the second layout and in the third layout the "slow" version only works the first method.
Is not possible to have in the same layout file the same letter in two layouts?

**Comment by MaethorNaur** [comment]
> Oh very nice. Is all programmed in the yaml file? When I try to program in the layout file the movement_sequence in the second layout and in the third layout the "slow" version only works the first method. Is not possible to have in the same layout file the same letter in two layouts?

Yes, you can have the same letters across different layers.

Not sure what you mean. If you provide the `movement_sequence` it won't be shown on the keyboard, unfortunately (with the release version)

**Comment by marcossmtp** [comment]
I use the command movement_sequence with letter á in second layout, and in the third layout I push the letter á in its position in the layout.
When I add this personal layout I can enter the letter á in the main layout using the secuence programmed with movement_sequence, but when I go to the layout where I enter the letter I can see it in the layout but not works with the "slow" method there. The other letters in that layout yes, but the one I repeated no.

**Comment by MaethorNaur** [comment]
Could you share your file?

**Comment by marcossmtp** [comment]
I use the command movement_sequence with letter á in second layout, and in the third layout I push the letter á in its position in the layout.
When I add this personal layout I can enter the letter á in the main layout using the secuence programmed with movement_sequence, but when I go to the layout where I enter the letter I can see it in the layout but not works.
 
I don't know how to add here a file. 
I share with pastebin:

https://pastebin.com/SRAp93Xi

**Comment by MaethorNaur** [comment]
Right the file is not valid.

There is a missing part for that letter

https://pastebin.com/Pa0YeJJc

**Comment by marcossmtp** [comment]
sorry, I can see the error, it was because I tried several times to get how it works , and the last was trying to put in different place the letter.
But with your correction I have the same problem it only works the method you write first. In that case it onl works the slow method, the short method not work with that file.

It's confirmed, it works perfectly, but I need to restart the app, kill it and reopen in my android oreo. I tried to load the custom file several times and doesn't work.
When I restart the app and load again it works fine.
And I can say, I dont know who has the idea to use yaml to configure the keyboard but I can say it was a great idea , its for me much clear to use than xml or json.
Thanks

**Comment by MaethorNaur** [comment]
I've tried both version releases and from the pr:

Release version:
[device-2023-06-13-122532.webm](https://github.com/flide/8VIM/assets/25067710/982e9ffd-fe50-444a-a458-8723b14d5511)

PR version:
[device-2023-06-13-122343.webm](https://github.com/flide/8VIM/assets/25067710/b7c9ed14-e5de-4842-81be-6d2329c1ae7e)

**Comment by marcossmtp** [comment]
yes, sure, now I reload in my android 13 phone and it works, but before in my android 8 no. 
I'm out now and I cant see if it was a problem of the mobile, perhaps it not load correctly before, I will see later but I tried several times and didnt work.
But in this mobile it works perfectly.
I don't know who has the idea of use yaml to configure the layouts but it is really a great idea, it's more clear than xml or json
Thanks

**Comment by marcossmtp** [comment]
Anyway it would be a good improvement that when you selected a file with a custom configuration layout this appear in the list of layouts as selected with the name of the file or if it is possible to named the layout with a key in the yaml file.
So you could add more than one custom layout and have them in the list of layouts and can selected or deleted from there.

**Comment by marcossmtp** [comment]
Is possible to make a layout hidden?, I thought it was using the command hidden: , but I'm not sure where to put if it is the correct method

**Comment by MaethorNaur** [comment]
Yes, for example:

```yaml
layers:
  hidden:
    - type: input_key
      movement_sequence:
        - top
        - no_touch
      key_code: shift_toggle
    - type: input_key
      movement_sequence:
        - left
        - no_touch
      key_code: switch_to_number_keypad
    - movement_sequence:
        - inside_circle
        - no_touch
      lower_case: " "
```

**Comment by marcossmtp** [comment]
Yes I took a look there, but if I put for example to hide the third extra layout:

third:
 hidden:
   sectors:
     top:
       parts:
         ........
it doesnt work . Isn't here where I have to put the hidden command?

**Comment by MaethorNaur** [comment]
No it has to be directly under `layers`:

More info: https://github.com/flide/8VIM/wiki/Adding-a-new-language#object-definitions

**Comment by marcossmtp** [comment]
So if I understand it, you can create layout with the name "hidden" that of course is hidden but only one no?
Hidden is a key like first, second.third..... not a property of a numbered layout
is that correct?, and in that case must be under layers 
And in that case must be the first layout programmed , must be under layers or can be set in other position

**Comment by MaethorNaur** [comment]
Yes `hidden` is a special layer when you don't want to render characters but are able to write them.

Then you have the `default` (first one). After that, you can define more layers to be rendered under `extra_layers`.

You can have up to 5 extra layers.

**Comment by marcossmtp** [comment]
ok thanks
But it must be in a fixed position the hidden layout or can be set in any position labeling that layout hidden?

**Comment by MaethorNaur** [comment]
It just needs to be directly under `layers`, like `default` or `extra_layers`. After if it's the first or last item of `layers` it doesn't matter

**Comment by marcossmtp** [comment]
oh ok all clear now
Thanks very much for your patience

**Comment by marcossmtp** [comment]
could you say me please why is not working this configuration?
I think all is ok, and I try of all forms
https://pastebin.com/wRCf2fVu

**Comment by MaethorNaur** [comment]
`second` is not indented correctly.

https://pastebin.com/hkqNw3Hf

**Comment by marcossmtp** [comment]
oh ok thanks very much
Now I have the custom file finish while is not ready the next versionis not ready.
Thanks again
