### ISSUE TITLE
Missing letters ü and â in Turkish layout

### ISSUE THREAD

**Issue by DeWir3** [8VIM/8VIM#323]
**Describe the bug**
I just noticed, that the Turkish layout is missing the letters ü and â on the 2nd layer. Ü is used a lot, and â is used e.g. in [hâlâ](https://en.wiktionary.org/wiki/hâlâ). It is not super common but where it is used it can be important, as "hala" for example is pronounced differently and has a different meaning.

**Comment by MaethorNaur** [comment]
Added missing letters in #322
