### ISSUE TITLE
No way to know which are multi-letter gestures

### ISSUE THREAD

**Issue by flauta** [8VIM/8VIM#328]
Even when the gesture pushes multiple characters (eg. "@gmail.com" or "!!!") on the layout only first char is always visualized. 

The only way to know where these symbols are, is to read YAML config file or to have a graphic help map.

I propose in this case to change color of the letter, to let at least the user know that it is a multi-character gesture.

**Comment by MaethorNaur** [comment]
This should be fixed with the next version (0.17.0)

**Comment by MaethorNaur** [comment]
The new RCs should have fixed that 👍
