### ISSUE TITLE
holding down CTRL to move by words

### ISSUE THREAD

**Issue by levigutt** [8VIM/8VIM#333]
**Is your feature request related to a problem? Please describe.**

When editing text I move the cursor around a lot. Tapping where I want the cursor to be will often miss, and using arrow key inputs is very slow (moving a single character at a time). 

When editing text on a computer, I usually use Vim where I can move by words using `w` and `b`. Outside of Vim I can hold down `ctrl` (or `option` on mac) and use the arrow keys to move by whole words. This is a fast and good way to navigate text.

Tapping `ctrl` in 8vim lets me do the same, but `ctrl` is only down for the next input. So after inputing an arrow key (by striking from the center and out in the desired direction) I have to press `ctrl` again to keep moving by words. If I need to move more than 1-2 words, I just don't bother. 

**Describe the solution you'd like**

I'd like a way to hold down the `ctrl` key. Maybe by holding the `ctrl` button for 1 second to lock it (and tap it to release), or tapping it twice (similar to shift; and likewise a third tap turns it back off). 

I think this would also work well when selecting text. 
Since there are two "available" spots on this panel (see screenshot), one of them could be used for Ctrl, and with a way to hold it down it would be easy to select a lot of text by selecting whole words at a time. 

**Describe alternatives you've considered**

Tapping the `ctrl` key again and again. 
Or zooming in on the text so I can tap more precisely and place the cursor where I want. 

**Additional context**

<img width="337" alt="image" src="https://github.com/flide/8VIM/assets/16719598/ebfb4518-f304-452a-a1d6-a832f6da4453">

**Comment by MaethorNaur** [comment]
Resolved with: #59, #386
