### ISSUE TITLE
latest version stops accepting input if I hesitate (move back to center before finish a letter)

### ISSUE THREAD

**Issue by levigutt** [8VIM/8VIM#334]
**Describe the bug**

If I type the word "subsequent", and start moving for a `c`, but then remember the word is spelled with a `q` so I move back to the center and go for the `q` instead. This worked fine before, but since updating to the latest version I'm left with only `subse`. The inputs stop If I move back to the center without finishing a letter.

Iteration 11 did not have this bug. I experienced it first in iteration 13. Iteration 12 never worked for me, so I don't know if it was present there, but I thing so since this might be related to the new way of handling layouts (with yaml instead of xml). 

I love the 8vim keyboard since I can type almost without looking at the screen - very useful for sending a quick message while busy with something else. But when I look to confirm the text before sending I now will often have a lot of half-written words due to this bug.
This makes 8vim a lot less useful to me :( 

**To Reproduce**

See uploaded video. 

The bug is present with any letters, but for an example I use `s`: 

1. move finger from center and up
2. move finger back down to center
3. move finger up again
4. move finger to the left
5. move finger to center to complete the `s`
6. no inputs happen

**Expected behavior**

I expect an input of `s`

**Screenshots**

Screen-recording of bug (iteration 13):
https://github.com/flide/8VIM/assets/16719598/e694ce10-f1ad-43af-ab33-666acada55b0

Screen-recording of expected behaviour (iteration 9):
https://github.com/flide/8VIM/assets/16719598/7c1f728e-cce2-45c7-9a29-f791b414b0fa

**Smartphone (please complete the following information):**

 - Device: FairPhone 4
 - OS: CalyxOS 4.10.0
 - Version: iteration 13

**Additional context**

The working screen-recording if from iteration 9, since I could not find iteration 11 for download. But it also worked fine in iteration 11.

**Comment by MaethorNaur** [comment]
PR created for that 😄
