### ISSUE TITLE
Failed to open settings for 8vim

### ISSUE THREAD

**Issue by ManDay** [8VIM/8VIM#370]
8vim 0.14.0 Android's (LineageOS's) input settings don't open 8vim's settings any more. A click on *8vim* in the input methods overview brings up a pill saying

> Failed to open settings for 8vim

Opening 8vim's settings dialog through the launcher still works. I can't say with certainty at which version it stopped working.

**Comment by MaethorNaur** [comment]
Hi, I'm going to have a look. Which android version are you running on?

**Comment by ManDay** [comment]
LineageOS 19-20230725-NIGHTLY-sargo (on a Pixel 3a). Thanks!

**Comment by MaethorNaur** [comment]
I suppose you are getting the keyboard from F-droid?
Do you have installed the google play services, I'll try to replicate the issue but as I don't have a LineageOS phone at my disposition

**Comment by ManDay** [comment]
Yes, from F-Droid. No Google Services installed. If you can confirm that 0.14.0 opens the settings dialog, coming from the input methods screen, that would already help. Then I can investigate on my end and find at which point it regressed.

**Comment by MaethorNaur** [comment]
So if I understood correctly, you get the error when you try to switch inputs?
Could you record your screen to understand correctly how this happens? 

Thanks

**Comment by ManDay** [comment]
https://github.com/8VIM/8VIM/assets/1059827/963e6f53-411c-4812-ae03-1ab3613b93d5

**Comment by MaethorNaur** [comment]
I noticed that but wasn't sure it was a bug. I know where to search know. thank you

**Comment by MaethorNaur** [comment]
Should be fixed on the the latest RC

**Comment by ManDay** [comment]
I take the liberty to close this for you as it seems to be fixed like you said it was.
