### ISSUE TITLE
Bug: empty view on hidden gestures without extra layers

### ISSUE THREAD

**Issue by martin-braun** [8VIM/8VIM#378]
**Describe the bug**
When a custom map has `default` and `hidden` layers, but no `extra_layers` the keyboard will remove all letters when attempting to draw a hidden move. In previous versions it would always show the `default` layer which should be the desired outcome when none of any `extra_layers` are defined.

**To Reproduce**
1. Use this custom layout: https://gist.githubusercontent.com/martin-braun/3e3948413ba76532ada4956a223c5ad2/raw/03e7c4d43d09236907c835d9069fb26c7107adf3/de_regular_german_kjoetoms-time-moves-1_mb-h4cker-edition_de60-en40_ext.yaml
2. Attempt to draw something from the hidden layer

**Expected behavior**
The letters on the grid should stay visible.

**Screenshots**

https://github.com/8VIM/8VIM/assets/24259245/e9be9d7a-287b-4d1e-bf59-c6603edfa99d

**Comment by kjoetom** [comment]
I've noticed that, too, and I can confirm it. That is - at least for me - quite distracting.

**Comment by MaethorNaur** [comment]
Should be fixed on the latest RC apk (available on the release page)

**Comment by martin-braun** [comment]
Thanks, yes, the RC version is working, hopefully the next release is not far away. Good job! :)
