### ISSUE TITLE
Haptics can no longer be disabled 

### ISSUE THREAD

**Issue by mtivi** [8VIM/8VIM#383]
**Describe the bug**
I have haptics disabled in settings. Haptics happen.  

**To Reproduce**
1. Go to settings 
2. Toggle haptic feedback off

**Expected behavior**
Typing will not create haptic feedback

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google pixel 5
 - OS: Android
 - Browser: issue not limited to browser 
 - Version 13

**Additional context**

**Comment by MaethorNaur** [comment]
Thanks for the report. I found the bug.
If you want to disable the haptics disable the sound "keypress sound" option (I swapped by mistake those two)

**Comment by MaethorNaur** [comment]
Should be fixed in the new RC

**Comment by mtivi** [comment]
Thanks! everything seems to be working now, 

sorry for the delayed reply

**Comment by MaethorNaur** [comment]
No worries
