### ISSUE TITLE
toggle selection mode in arrows board?

### ISSUE THREAD

**Issue by goyalyashpal** [8VIM/8VIM#386]
arrows board is always in selection mode. so there is no way to move cursor from the keyboard 

https://github.com/8VIM/8VIM/assets/19423063/30ffbef8-a4a0-4c32-aa51-ad0cca69fdb8
 

which makes the switch difficult for those coming from non-mainstream but much more sensible keyboards which feature things like:
* space _swipe_ cursor move
* delete _swipe_ 
this is far _far_ better than #59 

<img src="https://github.com/8VIM/8VIM/assets/19423063/b5e92378-7f85-4cca-8238-92f1f29f0632" width=250px/>

----
P.S.
* tap on center to "flip selection cursor" is brilliant
* i often miss this in my current keyboard: https://github.com/rkkr/simple-keyboard/issues/321#issue-1047049571

**Comment by goyalyashpal** [comment]
Illustration of simple keyboards swipe gestures for cursor, deletion, & selection


https://github.com/8VIM/8VIM/assets/19423063/5c1eff1b-646f-44f5-8236-94a9b09e920e

**Comment by MaethorNaur** [comment]
So currently if you move from the centre to the left/right. you move.
If I understand, do you also want to move from the select page (arrows)?

**Comment by MaethorNaur** [comment]
[Screen_recording_20230908_222233.webm](https://github.com/8VIM/8VIM/assets/25067710/4387d14a-0643-44b4-b2c5-91454b7c503e)

**Comment by goyalyashpal** [comment]
> If I understand, do you also want to move from the select page (arrows)?

 yes.

the swipe to move from circle has a too long trigger time - which i guess is to avoid conflicts with casual swipe vs swipe to move; so, i would prefer using dedicated page (which in this case would be the arrows)

**Comment by MaethorNaur** [comment]
@goyalyashpal I've proposed an idea on: #59

**Comment by MaethorNaur** [comment]
@goyalyashpal  In PR #403 I've added a new option (default to character by character) to control how the cursor should move.
It's always possible to toggle from the keyboard.
Shift now can select the text when the cursor moves

[output.webm](https://github.com/8VIM/8VIM/assets/25067710/57477752-a50d-4d44-9d13-77530808fe1e)

**Comment by goyalyashpal** [comment]
> default to character by character

but the shown is word by word right?

**Comment by MaethorNaur** [comment]
Both on the video

**Comment by MaethorNaur** [comment]
New feature available in the latest RC: https://github.com/8VIM/8VIM/releases/tag/v0.15.0-rc.16
