### ISSUE TITLE
Backspace does not work in some apps

### ISSUE THREAD

**Issue by cloneroom** [8VIM/8VIM#394]
It works in most apps, but backspace does nothing at all in google sheet and samsung notes. (I assume similar 'document editing apps' could be affected as well, but I haven't tested any others.) This is the case for all instances of backspace.
It worked before in previous versions.

Smartphone:
 - Device: Samsung Galaxy A13
 - OS: Android version 13

**Comment by KUKARAF** [comment]
Same in termux. Backspace does not seem to do anything. I tested with both 0.15.0-rc.6 and 0.15.0-rc.12

**Comment by MaethorNaur** [comment]
Thanks for the feedback, I'm going to have a look :)

**Comment by MaethorNaur** [comment]
I suppose is that button:
![Screenshot_20230929_213825](https://github.com/8VIM/8VIM/assets/25067710/e7f2333a-bc76-4081-b8bf-0336e811d915)

**Comment by MaethorNaur** [comment]
Should be fixed: https://github.com/8VIM/8VIM/releases/tag/v0.15.0-rc.13

**Comment by MaethorNaur** [comment]
Let me know if the issue is resolved. (I've only tested on termux)

**Comment by cloneroom** [comment]
It's fixed, thanks
