### ISSUE TITLE
Improve UI Experience

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#4]
Right now the UI for the keyboard is grotesque. 

Any suggestions, any help is more than welcome.

**Comment by AlecLangford** [comment]
The Menu on the left should auto hide or have a hide check box, the circle needs to be resizeable, and the original 8pen had a dark theme

**Comment by flide** [comment]
Well, I already have opened a issue, ages ago, regarding the circle re-sizable option, and yea maybe at some point the keyboard can have themes.

But, this experiment, whose name I keep changing everyday and currently, "vi8" is not exactly a plain and simple clone of 8pen. In the market today, it is hard to find phones that have less than 5.5" screen real estate, and of this particular kind of keyboard that means enormous amount of width to work with, which I feel is not really required. that is why there is a non intrusive side-bar. Maybe I can think of making it configurable, as in left or right, but I feel it is an essential part of the keyboard and cannot be simply "hidden".

I plan to add fonts and editing tools, like bold/italics/underlines etc, to the keyboard and this sidebar provides me the container where I can put the launch points for such features. So no... no hiding the sidebar.

**Comment by CaptainBlagbird** [comment]
Some thoughts/brainstorming:

- +1 for dark mode or other custom colors/backgrounds

- It might be interesting to have an option for multiple levels of detail/information:
  - Level 0: Only show empty background
  - Level 1: All letters off, only show the circle/cross
  - Level 2: As it is currently, show circle/cross and letters
  - Level 3: Show circle/cross, letters and symbols for sector tapping actions (see example in [Xpen](https://github.com/CaptainBlagbird/Xpen) screenshot)

- Personally I like the menu bar, but having the option for it to be on the right would be useful for left-handed people

**Comment by flide** [comment]
okay, so sidebar configuration, circle resize and circle position resets are done.

@CaptainBlagbird, your second point is interesting but given that currently we need focus on helping more people to understand the keyboard first, then to serve the most experienced among us, I am going to table that enhancement for some time (sorry for that!)

What else can we do to improve the the keyboard? since you guys have been using it regularly (hopefully!!), what are the major pain points?

**Comment by CaptainBlagbird** [comment]
That's ok, I just wanted to put my ideas here before I forget them. I totally agree, usability comes first, and style/design comes next.

To be totally honest, I don't use 8vim as much as I'd like to. There are three main reasons:

1. #20, 95% of the time I write (Swiss) German, where almost all sentences contain an umlaut (äöü). Switching keyboard for these letters kills the flow and using ae/oe/ue just looks and feels wrong :/
2. I'm not so fluent in using it anymore as I was years ago. Back then I learned it through the 8pen game. I prefered the game during free time over learning by using the keyboard for normal conversations (because usually I want to reply quickly).
3. #62, it's not really a issue for experienced users, but for me it happens from time to time because I'm not so experienced yet, and this totally breaks the flow since the cursor has to be changed again befor I can continue writing.

**Comment by mk-f** [comment]
Hi, I am new to this kind of keyboard and therefore really slow at the moment as I still have to look up how many quadrants I have to traverse for a given character.

It would greatly help, if a live preview of the character you would end up with when returning from the current quadrant would be displayed in the circle. 

I also would love to have an option to disable vibration (#71), and maybe a visual cue instead (e.g flashing of the circle)

**Comment by flide** [comment]
@mk-f Welcome to the community! 

A live preview would definitely be great, but where should such preview be shown?

**Comment by mk-f** [comment]
> @mk-f Welcome to the community!
> 
> A live preview would definitely be great, but where should such preview be shown?

Thanks! Like i said, the preview could be in the middle of the circle:

![8vim_preview](https://user-images.githubusercontent.com/18173863/97851729-0a94f980-1cf6-11eb-85cf-7bff0c4e36b0.png)

When moving out of the right quadrant into the top one, 'o' would be replaced with 'u'.

**Comment by BruceMustache** [comment]
> that is why there is a non intrusive side-bar. Maybe I can think of making it configurable, as in left or right, but I feel it is an essential part of the keyboard and cannot be simply "hidden"

@flide I don't thing side bar is essential
should have a option to hide it

**Comment by flide** [comment]
let's say you don't use it, let's say you have no interest in emoji's or using the selection keypad. 

- do you think **nobody** wants it? 
- is it really that intrusive that you are not able to type because of it? 

I agree that currently it does not serve a huge purpose and is filled with useless buttons but that is suppose to change in the future. I plan to convert it into a drawer for functionality like clipboard manager or macro launch points etc.

**Comment by BruceMustache** [comment]
But just should have a option to disable it if user wants

**Comment by flide** [comment]
too much work, too little return.
