### ISSUE TITLE
Swipe-out gestures involuntarily applied on swipe-out termination

### ISSUE THREAD

**Issue by ManDay** [8VIM/8VIM#412]
In the recent version of 8vim, there seems to have been a change which allows swipe-out gestures (e.g. C->L for "Move cursor left" or C->B for "Hide keyboard" to be chained onto regular input sequences. This creates an ambiguity with the method of terminating a sequence *without* space, where you would swipe out of the center on the last char.

Example: If you want to type "y" without a trailing space, you'd go C->T->R->C->L, but now this brings the cursor to the left of "y".

**Comment by MaethorNaur** [comment]
Should be fixed on: https://github.com/8VIM/8VIM/releases/tag/v0.16.2.
Might take some times to be available on F-droid though
