### ISSUE TITLE
Unable to delete single letters

### ISSUE THREAD

**Issue by kjoetom** [8VIM/8VIM#416]
**Describe the bug**
I am currently using version 16.2 of the 8vim-keyboard. Somehow it is no longer possible to delete single letters. Is this behavior intentional?

**To Reproduce**
1. Write some words
2. Tap in the right quadrant to delete backwards
3. Everything up to the previous word is deleted, even if you put the cursor somewhere inside a word

**Expected behavior**
Single letters should be deleted.

**Desktop (please complete the following information):**
 - Version [8vim16.2 from FDroid]

**Comment by MaethorNaur** [comment]
Make sure if Ctrl is underline or not. if it is, it's the expected behaviour (move/delete word by word)

**Comment by kjoetom** [comment]
You are totally right. 
My apologies for reporting something which obviously was a feature and not a bug.

**Comment by MaethorNaur** [comment]
> You are totally right. My apologies for reporting something which obviously was a feature and not a bug.

I got inspired by apple 😆
