### ISSUE TITLE
v0.16.0 onward do not show other layers

### ISSUE THREAD

**Issue by hyperglue** [8VIM/8VIM#418]
**Describe the bug**
Hi there!
Version 0.16.0 and onward (starting with rc.1) do not show layout of other layers as shown in the video below.
Version 0.15.0 works correctly.

https://github.com/8VIM/8VIM/assets/119142938/a4212a8f-33e5-46c6-95db-29282e95f1e1

**To Reproduce**
1. Swipe `bottom` to `circle` to `bottom`
2. It should show other layer
3. It does this on the version 0.15.0
4. On version 0.16.0-rc.1 onward it only shows another layer after blind selecting of character

**Expected behavior**
Other layer would show up just like in version 0.15.0, so instantly after finishing the `bottom` to `circle` to `bottom` gesture

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: DivestOS 20 / Android 13
 - Version: 0.16.0-rc.1 onward

**Comment by hyperglue** [comment]
I've tried building the newest version without changes from between 0.15.0 and 0.16.0-rc.1 and it seems that this patch here is responsible for the bug: 
https://github.com/8VIM/8VIM/commit/48441644a24206283cb88b6ad96056b55d67243e#diff-f32c76781c31eed2fa133e92966fa0b98813e5cc0b9c3c071b2a7da194cd7609

Changing `val layerLevel = LayerLevel.values()[i + 1]` back to `val layerLevel = LayerLevel.values()[i]` fixes the bug.

**Comment by MaethorNaur** [comment]
Fixed on the new release: https://github.com/8VIM/8VIM/releases/tag/v0.16.3
