### ISSUE TITLE
Borders not set correctly 

### ISSUE THREAD

**Issue by acorreya** [8VIM/8VIM#42]
The edges of vi8 are clipped off making out difficult to guess words at the periphery. 
![Screenshot_20201016-034836_Fennec](https://user-images.githubusercontent.com/3225091/96191824-822b0080-0f62-11eb-861a-f9bacd410a18.png)

**Comment by flide** [comment]
Bug noted, will take a look.

**Comment by denilsonsa** [comment]
Using the version from F-Droid on a 10" tablet:
![Screenshot_20201105-195257_8Vim](https://user-images.githubusercontent.com/121676/98284241-1e17bd00-1fa1-11eb-9ca3-d46e24177bef.jpg)
![Screenshot_20201105-195303_8Vim](https://user-images.githubusercontent.com/121676/98284252-21ab4400-1fa1-11eb-8bf0-a1c8af8d5c6b.jpg)

**Comment by acorreya** [comment]
Hi Ravi, not sure if this is dependent on the dpi setting. I use a high dpi on my device and maybe that's what cutting off the edges of keyboard? 

420 dpi
![Screenshot_20201201-013128693](https://user-images.githubusercontent.com/3225091/100658459-1adfd900-3375-11eb-8aaa-7251cc8757c7.jpg)

590 dpi
![Screenshot_20201201-012653003](https://user-images.githubusercontent.com/3225091/100658479-23381400-3375-11eb-82ad-476170aa65f7.jpg)
