### ISSUE TITLE
Buttons of app (not the keyboard) don't work

### ISSUE THREAD

**Issue by m-rey** [8VIM/8VIM#44]
When I open the app and press one of these 4 buttons, 
![Screenshot_2020-10-16-02-30-26-865_inc flide vim8_1](https://user-images.githubusercontent.com/42996147/96219451-27f06680-0f87-11eb-9069-d29a2d03c5cb.jpg)
nothing happens.

I'm using the app version `iteration-2`, which is offered here: https://f-droid.org/packages/inc.flide.vim8/
On a Xiaomi Mi Note 10 Pro, running MIUI 12.0.1.0 (Android 10).

**Comment by flide** [comment]
Yea, as of iteration 2 they are dummy buttons (sorry for that!!), already fixed in iteration 3 (to be release soon).
