### ISSUE TITLE
[feature request] add loop to insert space

### ISSUE THREAD

**Issue by m-rey** [8VIM/8VIM#46]
Currently, to add a space, the finger has to be lifted on the dot. This has the disadvantage, that you need to lift up the finger to start writing the next word.

It may feel more natural if there's a loop users could use to insert a space without having to lift their finger. People could then write whole sentences in one swipe.

**Comment by flide** [comment]
think of the ergonomics, space is the most common character in the language, hence it is assigned the shortest possible key for input. if we add a loop to insert space, the typing will take longer not the other way around.

I appreciate your thought process, but this is not something I will be implementing.

**Comment by WuerfelDev** [comment]
A possible solution could be to add a field to the sidebar which can be used with the other hand
This is how I did it:
![photo_2020-10-16_16-39-53](https://user-images.githubusercontent.com/12686819/96272332-3e6de080-0fce-11eb-8c55-d1e09f84d933.jpg)

**Comment by flide** [comment]
it's a nice idea.
What i want to do with the sidebar is add a drawer button to it, that will open up and present the user with more keys that are not frequently used like esc, or function keys.
Once that is in place, we can allow the user to customize the buttons on the sidebar that he/she wants to user frequently. After that feature we may get to the point you are showing @WuerfelDev 

By the way, nice color scheme, should think about configurable color scheme also...
