### ISSUE TITLE
[Regression] Swipe-out gestures involuntarily applied on swipe-out termination

### ISSUE THREAD

**Issue by ManDay** [8VIM/8VIM#469]
This reopens #412

**Comment by Ahruvon** [comment]
Having same issue. I was used to cursor movements being more 'deliberate' so to speak. Now, paired with cursor moving  out of text field, my daily use and writing has worsened.

**Comment by ManDay** [comment]
Yes, it's quite annoying. Especially since I'm trying to adapt to the "dynamic circle" feature which requires me to "abort" quite frequently. Now evey "abort" triggers a undeliberate gesture, which made me switch off "dynamic circle" for the time being. I figure this might just be a good case for an automated test @MaethorNaur :grin:

**Comment by MaethorNaur** [comment]
@ManDay @Ahruvon Does the APK from #471 fixes that issue?

**Comment by MaethorNaur** [comment]
Add a "fn" button to trigger special movements like moving the cursor/hiding the keyboard,... If it's toggle those movements will be triggered as usual (AKA when removing the finger) otherwise they won't

**Comment by ManDay** [comment]
> @ManDay @Ahruvon Does the APK from #471 fixes that issue?

Yes for me.

**Comment by Ahruvon** [comment]
> @ManDay @Ahruvon Does the APK from #471 fixes that issue?

@MaethorNaur 
Yes for me too! The toggle is a nice addition 😊
