### ISSUE TITLE
Set configurable keyboard height

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#47]
The user should have a choice to configure the keyboard height to manage the screen real estate.

**Comment by Glitchy-Tozier** [comment]
Why exactly would the user want to have a higher keyboard? I can understand wanting to make it smaller, but nobody wishes for an extra-big keyboard.

![8vimhigh](https://user-images.githubusercontent.com/59611881/100459478-d11d9700-30c5-11eb-9db4-0d99d733646c.jpeg)

What I _do_ somewhat understand is that someone might want to make it smaller and then slide it left&right, on tablets for example.

**Comment by flide** [comment]
Well I was assuming that the user practices reason in daily life.

side note : how did you elongate the keyboard? that feature does not exist yet...

**Comment by Glitchy-Tozier** [comment]
>how did you elongate the keyboard?

Magic.


_(also, GIMP)_

**Comment by ManDay** [comment]
@Glitchy-Tozier I would like a "taller" keyboard to be able to use a larger circle. Currently, the vertical size is limiting the size of the sector cross, and while I can change the circle size in the settings, this shrinks the diagonal lines to the point where the text starts overlapping and becomes unreadable.

**Comment by guancio** [comment]
#359 should address this
