### ISSUE TITLE
Keyboard not working properly on Samsung Z fold

### ISSUE THREAD

**Issue by MaethorNaur** [8VIM/8VIM#485]
Interactions stopped being registered after the first input on Samsung Z Fold

**Comment by MaethorNaur** [comment]
@SleepyScribe The stable version relies on Java when the new version relies on Android compose.
I'll look it the differences.
Question could you try [Florisboard](https://github.com/florisboard/florisboard) on your Z fold and let me know if you have any issue typing like the current RC of 8VIM?

**Comment by MaethorNaur** [comment]
@SleepyScribe Does the latest APK from #483 work on a Z fold?
In the mean time I'll to get a hand on a Z Fold in order to test it

**Comment by Eanilsen** [comment]
I'm not sure if this is the correct way to chime in, but I'm also experiencing issues on my Z Fold 3, but only when using the outer screen and on the layouts containing the arrow keys and the symbols. The actual typing using the circular layout works fine.

I'm by no means an Android dev, but do let me know if there is anything I can check for you.

**Comment by MaethorNaur** [comment]
@Eanilsen That issue has already been reported. I don't have a Z fold 3 yet and on the Android emulator, it seems to work fine. I'm going to get a Z fold 3 soon to debug that issue :)

**Comment by MaethorNaur** [comment]
@Eanilsen @SleepyScribe This should been fixed on the latest RC (I bought a Z fold 3 to debug that issue 😄 )

**Comment by Eanilsen** [comment]
@MaethorNaur Sorry for not getting back to you before, but I will test it myself. Thank you kindly!

**Comment by Eanilsen** [comment]
@MaethorNaur It works perfectly fine now, thank you!

**Comment by SleepyScribe** [comment]
@MaethorNaur Can confirm, it works great! Thank you so much for taking the time (and money) to fix a bug on such a niche device. Most devs are still glossing over foldables, but I think that's going to change soon with how thin and durable they're becoming.

I still love my Fold 3, and I hope you get some use from yours! If the inner protector starts peeling, don't take it off. Most people say it's fine to do on the 3 and it is at first until the center of the screen begins to very slowly flake over time.

**Comment by MaethorNaur** [comment]
@Eanilsen @SleepyScribe No worries. I'm glad that's fixed.
I used to have an Oppo find n2 flip.
I'll keep the Z fold 3, but the main phone will still be my Nothing Phone 2
