### ISSUE TITLE
selection gesture no longer works

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#491]
**Describe the bug**
i have been used to selecting text using the 'right to centre and hold' gesture, it no longer selects text. 

**To Reproduce**
1. with in a text field, with some text
2. start from the right sector, move to centre and hold

**Expected behavior**
as the cursor moves left, the text should be selected with in the path of the cursor

**Smartphone (please complete the following information):**
 - Pixel 7a
 - android version 14
 - 8vim version 0.17.0-rc.18

**Comment by MaethorNaur** [comment]
It should be fixed with 0.17.0-rc.19
