### ISSUE TITLE
Add Github-Link Everywhere.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#51]
At least in the Play Store (and I think in the app itself), there's no link to 8Vim's GitHub-page. (https://github.com/flide/8VIM)

I suggest fixing that, so that more people know where to post their ideas and/or bugs.

**Comment by Glitchy-Tozier** [comment]
Also mention that it's an open-source application. As far as I can see, in the Play Store, it's never mentioned.
(On F-Droid it's obvious that it's open-source, so no need to add this there)

**Comment by flide** [comment]
Done! The changes on the google play-store should reflect it in a short while.
