### ISSUE TITLE
Allow to change sound feedback volume, with separation of crossing section sounds

### ISSUE THREAD

**Issue by Redo11** [8VIM/8VIM#516]
**Is your feature request related to a problem? Please describe.**
I like to have more feedback to my actions, but the sound of the cross section audio feedback is too loud and similar to the regular feedback sound

**Describe the solution you'd like**
Add volume sliders for both general feedback volume (Master channel) and cross section feedback sound volume

**Describe alternatives you've considered**
Crying under bed, switching to Gboard and just turning the setting off 

**Additional context**
Why not make the sound custom?
Awful idea, i know, but we can already make custom layouts.

**Comment by MaethorNaur** [comment]
On the debug version, the crossing/haptic can be set in #511.

Available from the private F-droid Repo: https://github.com/8VIM/fdroid (version PR: 511)

That version will be installed along with the release version, so no interference between both versions)
