### ISSUE TITLE
Text editing gestures are broken now

### ISSUE THREAD

**Issue by ArhaeG** [8VIM/8VIM#532]
In 1.16 I've been able to move my cursor through the text by middle-left or middle-right. In 0.17.2, this gesture selects text.
Right-middle which previously selected letters now selects one letter then opens up editor, which is frustrating. 
I can't use this app as an editor, and I can't find any option at all that'd fix it. It worked so well before the update

**Comment by MaethorNaur** [comment]
What is your device/android version?

**Comment by MaethorNaur** [comment]
@ArhaeG is it fixed on the last RC? (not available on google play sorry, but f-droid/release page)

**Comment by alterNERDtive** [comment]
Just for the record, F-Droid is still only presenting me with 0.16.3.

**Comment by MaethorNaur** [comment]
@alterNERDtive yes. f-droid update can take up to 3 days. nothing we can do about it, sorry (on the public channel)

**Comment by ArhaeG** [comment]
> @ArhaeG is it fixed on the last RC? (not available on google play sorry, but f-droid/release page)

I sure does, now I can honestly say the update is really great! Thanks!
