### ISSUE TITLE
Dash Gesture

### ISSUE THREAD

**Issue by MedwardR** [8VIM/8VIM#539]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A quick way to type the dash character (-)

**Describe alternatives you've considered**
New gesture: left, circle, right

**Additional context**
![Screenshot_20240612-135912_GitHub.png](https://github.com/8VIM/8VIM/assets/117788102/76d43cac-0349-4d00-9b43-9163ca01df91)

Thanks for the awesome app!

**Comment by MedwardR** [comment]
I guess while you're at it, you might as well also make `top, circle, bottom` the pipe character

![Screenshot_20240612-181744_GitHub.png](https://github.com/8VIM/8VIM/assets/117788102/3de7ffc8-9e98-4a46-8660-1d18d84fe918)

**Comment by ManDay** [comment]
The general idea is that if you're not happy with a layout, a gesture, or want to add a gesture, you can do that yourself by writing a [layout file](https://github.com/8VIM/8VIM/wiki/Adding-a-new-language) (including [special codes](https://8vim.github.io/docs/dev/custom-keycode/)).

Personally, I've had a problem with writing a layout which includes sector-based gestures like the ones you mention, but @MaethorNaur has already started looking at it as far as I know. If you run into any trouble while writing a layout file feel free to file an issue or seek help in the Matrix room!
