### ISSUE TITLE
link to the guide from github page

### ISSUE THREAD

**Issue by ygrek** [8VIM/8VIM#567]
I was not aware of https://8vim.github.io/docs/category/guides existence until I found it linked in one of the issues. If I am not mistaken there is no link to it from the main github page. I would suggest putting link in the description (top right) and into README.md

**Comment by MaethorNaur** [comment]
@ygrek what do you about the new readme? I've removed all subcategories and left just a link to the website.

**Comment by ygrek** [comment]
idk, it is your call, i would say it would help to have a screenshot and example movement shown in the readme (to attract interest and quickly explain what it is, then folllow up with link to the guide). But current readme is indeed not very useful because without seeing the layout of the keyboard it is hard to understand what all the subsections talk about anyway, so the change feels like overall positive
