### ISSUE TITLE
[Feature request] programmable entries accessible from side bar/tray or from gestures

### ISSUE THREAD

**Issue by reacherjack422** [8VIM/8VIM#57]
If you could squeeze an icon near the emoji icon in the side bar, and have that take you to programmable slots to enter custom text for easy access like: .com, email address, or anything else used frequently. 

I'm envisioning something similar to the implementation in Kboard: https://github.com/adgad/kboard

So:
- tap new icon
- tap blank field
- add custom text (like .com for easy access)
- tap custom text to change or delete

Thanks for all your work and all you do. Fantastic app. 

Possibly related to #54

**Comment by flide** [comment]
Hi @reacherjack422 , 

I think it is possible to add progrmable buttons in the side drawer, once it is set, but would it not be better if you could specify gestures on the keyboard, attached to user defined text, directy on the keyboard? 

drawer definately can be used as a seating for programable buttons... will have to think about it.

**Comment by reacherjack422** [comment]
Gestures would be nice (and I believe they were part of the app that your app was cloned from?) but I've honestly never tried anything similar so I'm unsure how they can be implemented.

I love gesture actions in general and would welcome any solution that might allow adding quick shortcuts.  

Something nice about custom text shortcuts that I always use when possible is for longer strings of stuff like posting forum embed codes, markdown tags, forum bolding and quote tags, etc. Things that are cumbersome with any keyboard.

**Comment by flide** [comment]
To the best of my understanding, what you want would be best handled by a feature I call "clipboard manager" which i plan to implement in the keyboard. It will be a space where you save clips, copied text etc.

That is what you want right?

**Comment by reacherjack422** [comment]
@flide Yes, that's basically what I would want. I feel dumb since what I am wanting is essentially a clipboard with some level of pinning to save the clips from accidental deletion. So basically #3 

I can delete this issue if you want, unless it is different from the other issue enough to leave open
