### ISSUE TITLE
Don't allow inputMethodService to send characters when the keyboard is not visible

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#58]
In some scenarios, enter or backspace get perpetually pressed even if the keyboard is no longer visible. It makes the phone behave very strange. Make sure that the 8vim is not able to send any key if the keyboard ui is not visible.

**Comment by Glitchy-Tozier** [comment]
Ok, the only thing I would like to add is that it's not that it "shouldn't be allowed to send inputs". I feel like _it shouldn't be active at all. Disabled._
