### ISSUE TITLE
Cursor Movement should not possible after starting to write a word

### ISSUE THREAD

**Issue by CaptainBlagbird** [8VIM/8VIM#62]
Cursor movement emulation should only be possible when starting in the circle and moving to a sector.
Cursor movement emulation should not be possible when some letters were already written and the finger was not lifted since then.

Example:

I want to write "Hello", so I start in the center, move left, move down, move right, move back to the circle, without lifting the finger I move down, left, back to the circle, without lifting finger I move down. Now because I forgot, I wait some time to check where I actually have to move to, but because I am waiting, the keyboard interprets that as Move Cursor Down (Circle > Down > Wait).

It's kind of hard to explain, I hope you get what I mean. Please tell me if you need a better explanation... xD

**Comment by WuerfelDev** [comment]
See #11

**Comment by flide** [comment]
Yea this one is done, will be available in app stores after 30th of this month.
