### ISSUE TITLE
Moving back to the previous sector breaks flow until finger is lifted

### ISSUE THREAD

**Issue by CaptainBlagbird** [8VIM/8VIM#63]
How to reproduce:

1. Start in Center
2. Move to left sector
3. Move to bottom sector
4. Move to right sector
5. Instead of moving to the center (which would result in letter "h"), move back to bottom sector
6. Move back to center

&rarr; Actual behaviour: No letter is written, continuing without lifting finger has no effect, no more letters are written.
&rarr; Expected behaviour: Letter "i" is written, continuing without lifting finger writes the letters according to the movement.

Note: The expected behaviour is according to the original 8pen app (the full keyboard can still be tested in the 8pen game when pressing the two arrows on the bottom right of the level selection screen). And for me personally it's the most intuitive behaviour.

**Comment by flide** [comment]
Okay, let me clear this up.

8Vim is NOT a clone of 8pen, might have started it that way, but it is not a clone of 8pen anymore.

Now back to the original question.
I understand what you are trying to say and habit makes intuition, but what you are assuming in your argument there is a certain sequence of sectors that the fingers move through, like in your own example, you are essentially assuming there exist a natural sequence of sectors which can be backtracked. But this is not the case
`center -> left -> bottom -> right -> center`  
is **NOT** equivalent to 
`center -> left -> bottom -> right -> bottom -> center`

In my mind these are 2 different gestures.

Consider my argument : If during a movement, you have to stop, move "back" and then continue, the flow of the movement is already broken and in my experience it happens to be faster to start anew as the loops are not really that long. 
Also, not assuming any natural order opens up lots of opportunities to play with gestures, for example, the way I currently enter the Esperanto characters. For example to input 'ĉ' I do the following -
`INSIDE_CIRCLE;LEFT;TOP;RIGHT;TOP;RIGHT;INSIDE_CIRCLE;`

You may or may not agree with what I consider correct, but I don't think what you think as intuitive is actually intuitive. 
I will not be implementing the change you are expecting, sorry if that is disappointing.

**Comment by CaptainBlagbird** [comment]
Ah I see what you mean. I didn't realise that this was intended and used to support letter variations like ĉ.
That's good news for Custom Letter Layout ( #20) and Umlaut Support (#65) though :D
