### ISSUE TITLE
Add a Learning Mode

### ISSUE THREAD

**Issue by reacherjack422** [8VIM/8VIM#64]
I would say this is probably a low priority thing, but in the absence of a game to practice the keyboard with, it might be nice if the app has a Learning Mode.

It would look something like:

- open 8Vim app
- Select option for Learning Mode (among the other settings for "sidebar left" or "emoji keyboard" or "resize circle")
- learning mode would have different levels where Level 1 might only populate the keyboard with letters "a t n o i s y e"
- learning mode could give a list of words to practice like no, to, yes (this option could easily be left out since people can come up with their own words to test with the given letters)
- learning mode would allow you to practice in the "test your keyboard here" field

Edit: Learning mode would only be applicable to the 8Vim app. If the user left the app without turning off learning mode, the full keyboard will be displayed and usable in other apps

**Comment by flide** [comment]
It's a nice idea, but I plan to develop a whole game for the purpose of learning 8vim.
I need to find time to pen the idea down. Will happen soon.

**Comment by reacherjack422** [comment]
Awesome, thanks. A game will be better for sure.
