### ISSUE TITLE
Add a "About Page" in the settings applications

### ISSUE THREAD

**Issue by flide** [8VIM/8VIM#69]
Currently the small About page that is attached to the application gives very little information. We need to make it better.

A good idea would be try out [this](https://github.com/medyo/android-about-page) as a nice starting point.

**Comment by Glitchy-Tozier** [comment]
1. I think it would also be a good idea to put the GitHub-link into the app, to give users a quick way to check out the repository.

- Maybe in "About", you could add something like this to the end:
"8Vim is an open-source application. For feedback, you can visit the GitHub-repository: https://github.com/flide/8VIM"

- The only problem is: this also sounds a little bit like it belongs in the "Help & Feedback" -category. Not sure though.
The "Help & Feedback" -category seems a little unnecessary anyways, at least when it contains that few options.

2. In the "About" -Popup, some words seem to be randomly capitalized. For example, why is "Developed" capitalized? Should "Application" be capitalized?
3. There should be a space between "Designed and Developed by Filde" and "iteration 5". Currently it looks like, this is one sentence. "Designed and Developed by Filde iteration 5"
4. Maybe make it "Version: iteration 5"
