### ISSUE TITLE
[Improvement] Stop spamming "Please Activate IME"

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#70]
Giving users an easy option to switch keyboards is a good idea. However, it's currently a little much. To try it out, do this:
1. Set an other keyboard to be the currently used one.
2. Here's when the "Please Activate IME"-Popup gets triggered:

- When **opening the app** (which is the one popup that makes sense)
- When **re-opening the app** after having it run in the background (annoying but not a stupid decision)
- When clicking on "**Share 8Vim**" and then pressing the back-button to get back to the app
- When clicking on "**Help & Feedback**" and then pressing the back-button to get back to the app
- When clicking on "**Resize Circle**" and then pressing the back-button to get back to the app
- When clicking on "**Set Circle Center**" and then pressing the back-button to get back to the app
- AFTER **UNLOCKING THE SCREEN** (this is the most annoying one I think)
- When **rotating the screen**. (Please don't do this to users)

I suggest removing all those triggers except for the first one (opening the app). Instead, I suggest a "Switch keyboard" -button being placed somewhere within the app.

Also, normal users may not know what an "IME" is. I certainly don't. I suggest going for the fool-proof version of "_Please Activate 8Vim_"

Anyway, good job so far!  : )

(Tested on iteration-5)

**Comment by flide** [comment]
Very valid point!! I seem to have missed it because 8vim is my perpetual keyboard. 

Adding this as a bug. Thanks for the report.

**Comment by flide** [comment]
@Glitchy-Tozier , Can you please verify if this is still an issue on iteration-6?
This seems to have been fixed as part of some other change.

**Comment by Glitchy-Tozier** [comment]
Yeah, funnily enough it seems to be gone!
