### ISSUE TITLE
Improving the "About" -Popup

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#72]
1. I think it would also be a good idea to put the link into the app, to give users a quick way to check GitHub.

- Maybe in "About", you could add something like this to the end:
"8Vim is an open-source application. For feedback, you can visit the GitHub-repository: https://github.com/flide/8VIM"

- The only problem is: this also sounds a little bit like it belongs in the "Help & Feedback" -category. Not sure though.

2. In the "About" -Popup, some words seem to be randomly capitalized. For example, why is "Developed" capitalized? Should "Application" be capitalized?
3. There should be a space between "Designed and Developed by Filde" and "iteration 5". Currently it looks like, this is one sentence. "Designed and Developed by Filde iteration 5"
4. Maybe make it "Version: iteration 5"

**Comment by flide** [comment]
Hey, thanks for the suggestion, can you copy this to issue #69?

**Comment by Glitchy-Tozier** [comment]
Sure!
