### ISSUE TITLE
Make "Configurable Touch Trail"-Settings Responsive

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#73]
Two improvements to the "Configurable Touch Trail" -section:

1. Currently, the user has no clear indicator of what that option does. I think using it you can decide whether to use the color you have specified below, but I'm not sure. Therefore, if that option does what I think it does, I suggest:
If it's turned off, change the color-buttons to reflect their turned-off-ness. I can think of two options:
**a.** Make them go away. They're unused anyways. What i have in mind is this: make them "slide under" the "Configurable Touch Trail" -option, just as you would for example see the release-notes slide under the app-name in Play-Store -> My Apps & Games -> Updates -> click the small arrow next to the app-name
**b.** Gray out the buttons. I personally prefer option (a.), as it saves space, but this is open to discussion.

2. Please highlight the currently used color button. If you're currently not using 8Vim, you have not idea and no feedback, what touch-trail-color you're currently using.

Anyway, I love the new section, it's very pretty!  :)

**Comment by flide** [comment]
@DevamBhatia216 how about it? 
@Glitchy-Tozier 's idea makes way too much sense to not have been thought about by ourselves.
