### ISSUE TITLE
8Vim Screenshots are Distorted in App-Stores.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#77]
Both on F-Droid and the Play Store. Please fix this, it feels janky.

(see https://play.google.com/store/apps/details?id=inc.flide.vi8&hl=en&gl=us)
Example:
![image](https://user-images.githubusercontent.com/59611881/97786974-686af980-1baf-11eb-8b8b-c182858e90c6.png)

**Comment by flide** [comment]
Point Noted, I will try to fix this before next release.

**Comment by flide** [comment]
Is someone willing to provide nice screenshots for showcase on app stores?

**Comment by Glitchy-Tozier** [comment]
![8vimScreenshot1](https://user-images.githubusercontent.com/59611881/100208422-ffa24300-2f08-11eb-9a6d-f1ef724920b0.jpeg)

![8vimScreenshot2](https://user-images.githubusercontent.com/59611881/100208419-ff09ac80-2f08-11eb-8d2e-138da16adf17.jpeg)

**Comment by Glitchy-Tozier** [comment]
![8vimScreenshot3](https://user-images.githubusercontent.com/59611881/100212651-e6e85c00-2f0d-11eb-8211-e3a74b568bbd.jpeg)

![8vimScreenshot4](https://user-images.githubusercontent.com/59611881/100212648-e64fc580-2f0d-11eb-941a-0f6c862bd459.jpeg)

**Comment by Glitchy-Tozier** [comment]
Are those Screenshots ok?

**Comment by Glitchy-Tozier** [comment]
(Of course, They're old now)

**Comment by flide** [comment]
@Glitchy-Tozier I am really sorry. You put in effort and I did not even respond.

But, the screenshots are not okay. The screenshots are supposed to be framed with a phone, similar to what you see on the google play currently.

**Comment by ghost** [comment]
Could you provide me the smartphone overlay you used? I would try to add some screenshots for you.
Cheers,
Gecko

**Comment by flide** [comment]
Any overlay is good man, preferably the same phone on which screen shot is
being captured, to avoid any distortion.

**Comment by ghost** [comment]
I made some screenshots for Iteration 6 and created an overlay.
Please tell me whether the screenshots are ok.
Cheers,
Gecko

![8Vim-About](https://user-images.githubusercontent.com/45498399/102829241-f52f7800-43e6-11eb-8360-592553560976.png)
![8Vim-Mark](https://user-images.githubusercontent.com/45498399/102829242-f6f93b80-43e6-11eb-9473-598d75b38589.png)
![8Vim-NumPad](https://user-images.githubusercontent.com/45498399/102829243-f82a6880-43e6-11eb-9e89-1ef14ecfe0a3.png)
![8Vim-Prefs-Bottom](https://user-images.githubusercontent.com/45498399/102829246-f95b9580-43e6-11eb-9b4f-7d4cacf04533.png)
![8Vim-Prefs-Top](https://user-images.githubusercontent.com/45498399/102829249-f9f42c00-43e6-11eb-8d6f-716150bc6517.png)
![8Vim-XPad](https://user-images.githubusercontent.com/45498399/102829251-fb255900-43e6-11eb-90f9-09cecb329e78.png)

**Comment by Glitchy-Tozier** [comment]
I must say, the look good!

Of course the phone doesn't look absolutely high-tech, but on the other hand, i don't mind Fairphone getting some publicity.  :)

**Comment by ghost** [comment]
> I must say, the look good!
> 
> Of course the phone doesn't look absolutely high-tech, but on the other hand, i don't mind Fairphone getting some publicity. :)

Thanks 🙂 
I was told to use an overlay of the phone I made the screenshots with, so I would say: delivered as ordered.
And by the way my Fairphone runs LinageOS 17.1 which is based on Android 10. That way we should not have any problems with showing old interfaces. And I also think there are worse companies to promote in an open source project than Fairphone 😉 
In the end @flide has to decide whether these screenshots are good or not.

**Comment by flide** [comment]
Dude, this is good enough. Will update these on all both the stores. 


By the way, fdroid is not updating 8vim, isn't it?

**Comment by ghost** [comment]
Nice to hear that the screenshots are ok. Once Iteration 7 is ready I can easily switch the images to match the new interface.

F-Droid is still on Iteration 5 🙁 I used the apk from the release page to update to Iteration 6.

**Comment by flide** [comment]
I wanted to know if there is an easier way to generate these kind of screenshots automatically?
This becomes a chore with every UI update. Anyone any suggestions?

**Comment by ghost** [comment]
I created the screenshots in Gimp. It shouldn't be too hard to code a script that scales and locates the screenshots inside the phone frame and exports a PNG. But I'm not into Gimp scripting yet.

Anyway we first need the basic screenshots to begin with. I don't know if you can create these from the code itself.

**Comment by ghost** [comment]
@flide 
Would you like me to add a folder with the images (including xcf source files) to the repo and send you a pull request?

**Comment by flide** [comment]
Add that folder inside 'random images' folder for now.
