### ISSUE TITLE
Training game link not working

### ISSUE THREAD

**Issue by elig0n** [8VIM/8VIM#78]
In f-droid it is said that there is a training game but the link to the Play Store shows that the app was removed.

**Comment by flide** [comment]
Yea, it's quite possible. The game application was quite old and I did not own it.
Try searching it's availability on other app stores. 

Amazon : https://www.amazon.com/8pen-Ltd-Wordcup-game/dp/B006MMXK1G

**Comment by WuerfelDev** [comment]
I think the game is broken anyway, I experience problems in Level5 so i cant go beyond that
