### ISSUE TITLE
Disable auto-space

### ISSUE THREAD

**Issue by elig0n** [8VIM/8VIM#79]
I am just learning this and it is quite hard to see some letters when my hand is covering them. since it is required to swipe in succession to type a word and if I do it letter by letter a space is added automatically when I raise finger frok the circle. Maybe you can add an option to disable auto space?it can also be exerting to write long words without raising the finger or hard to draw a 3-4 sector circle on a large circle and screen after some nonstop swiping so I anyway have to let go and then delete the space.

**Comment by flide** [comment]
It is awesome to see a new user try. The learning curve is indeed pretty steep, but I promise it is worth the effort.
Auto-space, as you call it is an integral feature of the keyboard and helps you write. Disabling it will do nothing in your aid. Couple of hours of total practice and all will be good. 

Best of luck and Welcome to the community.
