### ISSUE TITLE
Make more buttons able to rapid-fire.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [8VIM/8VIM#83]
This applies to, for example,
- That reverse-backspace-key (normal backspace _can_ rapid-fire)
- The white/invisible keys, (which, if intended to do what they're currently doing, need some visual indication)
- The enter-button
- The paste-button. This is the most unfortunate to not be able to rapid-fire.

**Comment by Glitchy-Tozier** [comment]
Also, all the buttons in the 'selection keypad' only seem to have white popups ... should I create an issue for this as well?

**Comment by flide** [comment]
@Glitchy-Tozier , Please do create an issue for that white popups.

**Comment by Glitchy-Tozier** [comment]
Actually, as there are no Popups with multiple options, **all** buttons should be able to rapid fire when held.

**Comment by flide** [comment]
I have changed code to make the following buttons repeatable: 
- forward Delete button
- paste button
- Enter button

**Comment by Glitchy-Tozier** [comment]
Great work!
Hey, could we also fix that:
>Actually, as there are no Popups with multiple options, all buttons should be able to rapid fire when held.

Or do you want me to create a separate issue?

**Comment by flide** [comment]
The white popups is a separate issue, and will need a new issue. I think that is going to be a common issue for all the button based keyboards.

**Comment by Glitchy-Tozier** [comment]
I meant the "Let all the special-character-buttons rapid-fire"-request.

**Comment by flide** [comment]
well, after the update following buttons on selection keypad can't "rapid fire" :

- cut 
- copy 
- switch highlight
- switch to xpad 
- select all

It make no sense to have rapid fire on any of them. 

Rest all will fire away.

**Comment by Glitchy-Tozier** [comment]
I absolutely agree with you on that one. What I was talking about were those though. ;)

![Screenshot_20201208-114421_Omni Notes.jpg](https://user-images.githubusercontent.com/59611881/101474042-de027c00-394a-11eb-9ab3-54dbf7a77dcc.jpg)

(And the other special keyboards)

**Comment by flide** [comment]
ahh got it.

**Comment by flide** [comment]
you think all keys should be repeatable?

**Comment by Glitchy-Tozier** [comment]
Pretty much, yeah. Except for the `switch keyboard`-bottons of course.

It won't be a very commonly used feature, but i can't really see any reasons for not implementing it.

**Comment by flide** [comment]
understood. In hind sight it seems obvious.

**Comment by Glitchy-Tozier** [comment]
What do you think about `Space` being able to rapid-fire?

**Comment by flide** [comment]
everything rapid fires on long press on button keypads.

**Comment by Glitchy-Tozier** [comment]
I meant the circle on the x-pad.

**Comment by flide** [comment]
possible... but difficult.
Can you raise a new issue for that ?

**Comment by Glitchy-Tozier** [comment]
Done https://github.com/flide/8VIM/issues/141
