### ISSUE TITLE
accessing settings from the gear icon from sidebar not working

### ISSUE THREAD

**Issue by khlsvr** [8VIM/8VIM#86]
Today I noticed pressing the 'gear' icon doesn't do anything. Also the "->" icon or "CTRL" icon don't do anything, but in case of the CTRL icon I guess it could be just that if it's supposed to emulate the keyboards ctrl key then I guess nothing should happen anyway. 

I did reboot my phone before I noticed the problem. After noticing the problem I went to the keyboard settings and tried to tap the "settings" under 8vim, but that doesn't do anything either, so I went to the 8vim icon on the phone's "desktop". That opens up the 8vim settings page as expected. Now there I try to "resize circle", but for some reason the circle is not changing size. I did resize it 2-3 days ago succesfully when I installed the app. I guess I try delete all data and see if that helps, or reinstall the app?

extra/off-topic:
I saw 8vim 2-3 days ago on f-droid front page and it seemed interesting and I decided to try it. I have been typing a bit, but not much so maybe it's that I haven't gotten experienced yet, but after say .. maybe 200-400 typed words now I do remember the layout quite well except 3rd or 4th sector ones I might not remember until after I think about it for one second or check the layout. Typing is slow which is not the problem at this point as a beginner, but rather that I am struggling to exit from the correct sector every now and then, (for example typing "r" when I meant "a")  so I am making typos. Is this something that I will get better at, or is this a common problem?  I was wondering that maybe some time in the future A.I. could learn from the size of curves I make in a way that I wouldn't need to know where the middle circle is or where the sector limits are and typing would become easier?

The other more urgent improvements that I have thought about have been discussed here aswell, so I guess I can expect those in the (near?) future. Those would be the umlauts (I like the 4th proposal of the possible implementations), suggestion bar (that expands the dictionary from the words I have typed) and a clipboard. I want to mention that I am an avid user of the swiftkeys sticky clipboard items. Meaning that I have added some words (or special utf8 chars) as sticky items that I use alot and then access them from the clipboard list. Also I like the idea of the feature some user mentioned about skipping vowels on words allowing them to appear on the suggestion bar. I would definitely give that a try if it was available. 

edit: I have Xiaomi Redmi Note 7 with MIUI Global 11.0.5 and Android version 10 QKQ1...Today I noticed the circle size had changed, I tried changing it again but it didnt work right away, then after restarting 8vim (it didnt yet work) but then I did something else and when I got back to typing something the circle had changed.

**Comment by flide** [comment]
So, as I understand you faced 2 bugs
- setting changes not affecting the ui
- gear icon on the main keypad not working 

For the first one,  please see #36

For the second one, I might be missing something. The gear icon is suppose to open the settings activity, so if you are already there you won't seen any change. As I understand, the gear icon is working as expected ... I feel I have missed something.

**Comment by khlsvr** [comment]
Ok. Good to know the workaround for the first one. Here's a short video where I type.. or write(?) a text "testing" and then I try press the buttons on the left side. Two of the buttons do something visibly, the three other I haven't figured out what they do. One in the middle opens the keypad and the upper one opens google voice, which I have set as the emoji keyboard or what it was called. I wanted a quick access to that. https://imgur.com/a/k7aXyXS

**Comment by flide** [comment]
Interesting. 

I will try to figure out what is going wrong.

**Comment by flide** [comment]
Not able to replicate.
Need more instances of this misbehavior, to figure out how to replicate it.

**Comment by geofrey** [comment]
iteration-7 on a Samsung Galaxy S6 with Android 7.0. Tapping the gear icon tries to open a new screen but immediately crashes.

**Comment by flide** [comment]
The current application is targeted at android 11, and you are using
android 7, so it is likely some lib used in the UI page is not compatible.

Based on statistics from "
https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide
"
Android 7.0 holds less then 5% market share, (which is not insignificant)

I think I have hastily upped the target version and should support at-least
Android 6 .

I will try and do the necessary research.

**Comment by flide** [comment]
Okay I double checked, the minimum Android supported on 8vim is Android 5.
And I ran a test on an emulated device with Android 5.1, works with no
issues.
I also tested the app on an emulated Pixel device with Android 7.0. So it's
clearly not a android issue.

Not sure, how to figure this out.

**Comment by geofrey** [comment]
On one hand I in particular expect to replace this device soon so don't put
yourself out on my account. On the other hand I'm surely not the only one
with an old phone.

What more system information would be of use here?
