### ISSUE TITLE
[Feature] Add numbers

### ISSUE THREAD

**Issue by Tau5** [8VIM/8VIM#87]
I discovered this keyboard on f-droid and I've been using it. As far as I know it isn't posible to input numbers
I think it's obvious that inputting numbers should be vital and by looking at the code I have not found how to input them either

**Comment by Tau5** [comment]
Ok, i didn't read all the README

**Comment by elig0n** [comment]
it could be nice to put the extra numbers and characters in their own similar circle layout

**Comment by flide** [comment]
Another circle make the board crowded and also 'number' are pretty evenly distributed, on the axis of frequency. no point to optimize it on 8vim style keypad. 

pressing the left sector should take you to numberpad.

**Comment by elig0n** [comment]
I actually meant to have numbers and perhaps other special symbols in their own circle , which will appear right after hitting the extra keys button which right now show them in a normal keyboard layout... we need a solid interface ;)
