### ISSUE TITLE
Brave Browser hides keyboard after one character entered

### ISSUE THREAD

**Issue by sslater11** [8VIM/8VIM#97]
When I go to type in the address bar, as soon as I return to the circle after choosing a letter, the search results show up and the keyboard disappears. I can continue to type a whole word on the now invisible keyboard, but I can only type one word and that's it.

**Comment by flide** [comment]
@sslater11 , I did not find any such issue with the latest Brave Browser (Brave 1.16.76, Chromium 86.0.4240.198)

What version of Brave Browser are you using?

**Comment by sslater11** [comment]
Yeah, that's the version I'm using. It's not a constant problem. Sometimes the keyboard stays open, so not really sure what's making it disappear.

**Comment by sslater11** [comment]
Hmmm on testing, if I force close brave and reload it, it seems to let me use the keyboard, but if i do a search, then another search, the second time it closes the keyboard. I also have lots of tabs open in it.

**Comment by WuerfelDev** [comment]
Can you confirm that this does not happen with other keyboards? Could be a brave bug too

If it is a bug in 8vim it would likely happen in different applications too I think

**Comment by sslater11** [comment]
I can confirm it's an 8vim only bug.
Tested with AnySoftKeyboard, Compass Keyboard, Jbak2, Multiling O, and OpenBoard. I have no issues with any of those keyboards.

At lease for now we have a temporary solution, which is to just to force quit brave and then open it again.
EDIT: Also just opening a new tab seems to let me use the address bar.

**Comment by m-rey** [comment]
I can't reproduce the issue.
I've installed the latest Brave version 1.17.72 and 8vim works just fine on my end.

**Comment by flide** [comment]
@sslater11 I am not able to reproduce this bug. Can you post a gif/video of this happening?

**Comment by sslater11** [comment]
Funnily enough I can't reproduce this either! I guess give me a week and I'll pay attention to whether it pops up again and I'll see, and if it doesn't then I guess close this.
